// tools/generate_lang_codes_md.mjs
//
// Regenerates docs/words/LANG_CODES.md from the current LANG_DATA +
// LANG_NAMES + LANG_DATA[code].meta. Contributors run this whenever
// they add or rename a language entry.
//
//   node tools/generate_lang_codes_md.mjs

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function loadAll() {
    const sandbox = { window: {} };
    vm.createContext(sandbox);

    // Load wordmap_data.js and expose LANG_DATA
    const dataSource = fs.readFileSync(path.join(ROOT, 'wordmap_data.js'), 'utf8');
    const wrappedData = dataSource + '\nglobalThis.LANG_DATA = LANG_DATA;\n';
    vm.runInContext(wrappedData, sandbox);

    // Load lang_names.js and expose LANG_NAMES
    const namesSource = fs.readFileSync(path.join(ROOT, 'lang_names.js'), 'utf8');
    const wrappedNames = namesSource + '\nglobalThis.LANG_NAMES = LANG_NAMES;\n';
    vm.runInContext(wrappedNames, sandbox);

    // Load wordmap_meta.js (mutates LANG_DATA in place)
    const metaSource = fs.readFileSync(path.join(ROOT, 'wordmap_meta.js'), 'utf8');
    vm.runInContext(metaSource, sandbox);

    return sandbox;
}

function render(sandbox) {
    const { LANG_DATA, LANG_NAMES } = sandbox;
    const en = (LANG_NAMES && LANG_NAMES.en) || {};
    const ja = (LANG_NAMES && LANG_NAMES.ja) || {};
    const codes = Object.keys(LANG_DATA).sort();
    const rows = codes.map(code => {
        const lang = LANG_DATA[code] || {};
        const meta = lang.meta || {};
        const enName = en[code] || lang.name || '';
        const jaName = ja[code] || '';
        const fam    = meta.family   || '';
        const spk    = meta.speakers || '';
        return `| \`${code}\` | ${enName} | ${jaName} | ${fam} | ${spk} |`;
    });

    return [
        '# LangMap language codes',
        '',
        `Auto-generated by \`tools/generate_lang_codes_md.mjs\` on ${new Date().toISOString().slice(0,10)}.`,
        `Total: ${codes.length} codes.`,
        '',
        '| Code | English name | Japanese name | Family | Speakers |',
        '|------|--------------|---------------|--------|----------|',
        ...rows,
        '',
    ].join('\n');
}

const sandbox = loadAll();
const out = render(sandbox);
const outPath = path.join(ROOT, 'docs', 'words', 'LANG_CODES.md');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out, 'utf8');
console.log(`wrote ${outPath} (${out.split('\n').length} lines)`);
