/**
 * hello — see docs/words/CONTRIBUTING.md for editing guidance.
 * Language codes: see docs/words/LANG_CODES.md.
 */
WORDS.hello = {
  label: {
    en: "Hello",
    ja: "こんにちは",
    ko: "안녕",
    zh: "你好",
    yue: "你好",
    vi: "Xin chào",
    th: "สวัสดี",
    id: "Halo",
    hi: "नमस्ते",
    de: "Hallo",
    fr: "Bonjour",
    it: "Ciao",
    es: "Hola",
    es_eu: "Hola",
    es_mx: "Hola",
    pt: "Olá",
    pt_eu: "Olá",
    pt_br: "Olá",
    ru: "Привет",
    uk: "Привіт",
    ar: "مرحبا",
    he: "שלום",
    sw: "Habari",
  },
  definition: {
    en: "Neutral everyday greeting. Time-of-day forms (morning/evening) only if the language has no neutral form. Blessings (e.g. \"peace\") accepted only as the normal greeting.",
    ja: "中立的な日常挨拶。時刻別の挨拶 (おはよう・こんばんは) は中立形がない場合のみ。「平安」などの祝福語も、それが通常の挨拶である場合のみ。",
    ko: "중립적 일상 인사. 시간대별 인사 (아침/저녁)는 중립형이 없을 때만 사용. \"평안\" 등 축복어는 그것이 통상적 인사일 경우에만.",
    zh: "中性日常问候语。仅当语言无中性形式时才使用时段问候 (早安/晚安)。\"平安\"等祝福语仅在它本身就是日常问候时使用。",
    yue: "中性日常問候語。時間性問候（早晨／晚上）淨喺冇中性形時用。「平安」呢類祝福只喺佢本身就係日常問候時用。",
    vi: "Lời chào trung tính hàng ngày. Chào theo thời điểm chỉ khi không có dạng trung tính. \"Bình an\" chỉ khi đó là lời chào thường ngày.",
    th: "คำทักทายกลางๆ ประจำวัน; ใช้คำตามช่วงเวลาเฉพาะเมื่อไม่มีคำกลาง; ใช้คำอวยพร (\"สันติ\") เฉพาะเมื่อเป็นคำทักทายปกติ",
    id: "Sapaan sehari-hari yang netral. Sapaan waktu (pagi/malam) hanya jika tak ada bentuk netral; \"salam\" hanya jika itu sapaan biasa.",
    hi: "तटस्थ रोज़मर्रा अभिवादन। समय-आधारित अभिवादन तभी जब तटस्थ रूप नहीं है। \"शांति\" जैसे आशीर्वाद तभी जब वह सामान्य अभिवादन हो।",
    de: "Neutraler Alltagsgruß. Tageszeit-Grüße (Guten Morgen/Abend) nur wenn es keinen neutralen Gruß gibt; Segenswünsche (\"Friede\") nur, wenn es der übliche Gruß ist.",
    fr: "Salutation neutre du quotidien. Forme selon l'heure (matin/soir) uniquement faute de neutre; les bénédictions (\"paix\") seulement si c'est la salutation usuelle.",
    it: "Saluto neutro quotidiano. Forme orarie (buongiorno/buonasera) solo se manca un neutro; benedizioni (\"pace\") solo se sono il saluto abituale.",
    es: "Saludo neutro del día a día. Las formas por hora (buenos días/noches) solo si no hay neutro; bendiciones (\"paz\") solo si son el saludo habitual.",
    es_eu: "Saludo neutro del día a día. Las formas por hora (buenos días/noches) solo si no hay neutro; bendiciones (\"paz\") solo si son el saludo habitual.",
    es_mx: "Saludo neutro del día a día. Las formas por hora (buenos días/noches) solo si no hay neutro; bendiciones (\"paz\") solo si son el saludo habitual.",
    pt: "Saudação neutra do dia-a-dia. Formas por hora (bom dia/boa noite) apenas se não houver neutra; bênçãos (\"paz\") apenas se forem a saudação habitual.",
    pt_eu: "Saudação neutra do dia-a-dia. Formas por hora (bom dia/boa noite) apenas se não houver neutra; bênçãos (\"paz\") apenas se forem a saudação habitual.",
    pt_br: "Saudação neutra do dia a dia. Formas por hora (bom dia/boa noite) apenas se não houver neutra; bênçãos (\"paz\") apenas se forem a saudação habitual.",
    ru: "Нейтральное повседневное приветствие. Формы \"доброе утро/вечер\" — только при отсутствии нейтральной; благословения (\"мир\") — лишь если это обычное приветствие.",
    uk: "Нейтральне повсякденне привітання. Форми за часом доби — лише за відсутності нейтральної; благословення (\"мир\") — лише якщо це звичне привітання.",
    ar: "تحية يومية محايدة. صيغ الأوقات (صباح/مساء الخير) فقط عند غياب صيغة محايدة؛ صيغ البركة (\"سلام\") فقط إذا كانت التحية المعتادة.",
    he: "ברכת שלום יומיומית ניטרלית. ברכות לפי שעות (בוקר/ערב) רק בהיעדר צורה ניטרלית; ברכות הברכה (\"שלום\") רק אם זוהי הברכה השגרתית.",
    sw: "Salamu ya kawaida isiyo na ushawishi wa wakati. Salamu za saa (asubuhi/jioni) ikiwa hakuna umbo la jumla; baraka kama \"amani\" zinapokubaliwa kama salamu ya kawaida.",
  },
  data: {
    ja: ["こんにちは", "konnit͡ɕiwa"],
    ja_osa: ["毎度", "maido"],
    ja_aom: ["どうも", "doːmo"],
    ja_oki: ["はいさい", "haisai"],
    ja_hak: ["何ばしよっと？", "nambaɕotto"],
    ja_kyo: ["こんにちは", "konnitɕiwa"],
    ja_hir: ["やあ", "jaː"],
    ja_mvi: ["んみゃーち", "mjaːt͡ɕi"],
    ja_rys: ["おーりとーり", "oːɾitoːɾi"],
    ko: ["안녕하세요", "annjʌŋhasejo"],
    ko_kp: ["안녕하십니까", "annjʌŋhaɕimnikka"],
    ko_bus: ["안녕하이소", "annjʌŋhaiso"],
    ko_jeju: ["혼저옵서예", "hond͡ʑʌop̚sʌje"],
    ko_yb: ["안녕하십니까", "annjʌŋhaɕimnikka"],
    zh: ["你好", "ni˧˩˧xaʊ̯˧˩˧"],
    yue: ["你好", "neːi˧˩hɔːu˧˥"],
    nan: ["你好", "li˧˥ho˧˥"],
    wuu: ["侬好", "noŋ˩hɔ˧˩"],
    hak_cn: ["你好", "ngi˧˥ho˧˩"],
    vi: ["xin chào", "sin˥ t͡ɕaːw˨˩"],
    vi_c: ["xin chào", "siːn˥ t͡ɕaːw˧˨"],
    vi_s: ["xin chào", "siŋ˥ ɕaːw˨˩"],
    th: ["สวัสดี", "sa˨˩wat˨˩diː˧"],
    id: ["halo", "halo"],
    ms: ["hai", "hai"],
    hi: ["नमस्ते", "namasteː"],
    hns: ["namaste", "namaste"],
    sa_edu: ["नमस्कारः", "namaskaːɾaɦ"],
    sa: ["नमस्ते", "namasteː"],
    bn: ["নমস্কার", "nɔmɔʃkaɾ"],
    rkt: ["হামার সালাম", "hamaɾ salam"],
    ur: ["السلام علیکم", "assalaːmu ʕalaikum"],
    ta: ["வணக்கம்", "ʋaɳakkam"],
    iru: ["vannakkam", "vanːakːam"],
    en: ["hello", "həˈləʊ"],
    de: ["Hallo", "haloː"],
    fr: ["bonjour", "bɔ̃ʒuʁ"],
    pcd: ["bojour", "bɔʒuʁ"],
    nrf: ["bouônjour", "bwɔ̃ʒuʁ"],
    it: ["ciao", "ˈt͡ʃaːo"],
    es_eu: ["hola", "ˈola"],
    es_mx: ["hola", "ola"],
    pt_eu: ["olá", "ɔla"],
    pt_br: ["oi", "oj"],
    ru: ["привет", "prʲɪvʲet"],
    ar_qur: ["السلام عليكم", "as.salaːmu ʕalajkum"],
    ar: ["مرحبا", "marħaba"],
    he: ["שלום", "ʃalom"],
    tr: ["merhaba", "meɾhaba"],
    fa: ["درود", "doɾuːd"],
    jpr: ["שלום", "ʃɒːlom"],
    prs: ["سلام", "salɒːm"],
    trm: ["salaam", "salaːm"],
    sw: ["habari", "habari"],
    suk: ["mwangaluka", "mwaŋɡaluka"],
    nym: ["mwadita", "mwadita"],
    rim: ["mbukire", "mbukiɾe"],
    ksb: ["nashukuru", "naʃukuɾu"],
    jmc: ["máshàlòmà", "maʃalom"],
    sbp: ["mbasala", "mbasala"],
    rwk: ["kira", "kiɾa"],
    asu: ["shiloi", "ʃiloi"],
    tl: ["kamusta", "kamusta"],
    agt: ["kumusta", "kumusta"],
    mn: ["сайн уу", "sajn uː"],
    sah: ["дорообо", "doroːbo"],
    tyv: ["экии", "ekiː"],
    kjh: ["изеннер", "izenner"],
    alt: ["эзен", "ezen"],
    cv: ["салам", "salam"],
    bxr: ["сайн байна", "sajn bajna"],
    mvf: ["amur sain", "amur sain"],
    evn: ["дорообо", "doroːbo"],
    eve: ["дорова", "dorova"],
    gld: ["банди-банди", "bandi bandi"],
    ude: ["бандиба", "bandiba"],
    yrk: ["аньˮторова", "anʔtorova"],
    enf: ["anyo", "aɲo"],
    nio: ["нерум", "nerum"],
    sel: ["тӱла", "tyla"],
    kca: ["вуща", "wuɕa"],
    ckt: ["етти", "jetːi"],
    kpy: ["эймэӄ", "ejmeq"],
    itl: ["—", "—"],
    ykg: ["—", "—"],
    yux: ["льуоркэн", "lʲuorken"],
    niv: ["ӈафӄа", "ŋafqa"],
    ket: ["торова", "torova"],
    my: ["မင်္ဂလာပါ", "mìɴɡəlà bà"],
    km: ["សួស្តី", "suəsdəj"],
    lo: ["ສະບາຍດີ", "sa˨ baːj˩˧ diː˩˧"],
    soa: ["สบายดี", "sa˩˧ baːj˩˧ diː˩˧"],
    yo: ["ẹ kú", "ɛ kú"],
    zu: ["sawubona", "sawuɓona"],
    am: ["ሰላም", "sɛlam"],
    aiw: ["saro", "saro"],
    sgw: ["እንደምን", "ɨndɛmɨn"],
    mg: ["manao ahoana", "manau ahoana"],
    ain: ["イランカラプテ", "iɾankaɾapute"],
    fi: ["hei", "hei"],
    hu: ["szia", "siɒ"],
    ohu: ["ìstèn hozott", "iʃtɛn hozotː"],
    el: ["γεια σου", "ʝa su"],
    nl: ["hallo", "hɑloː"],
    pl: ["cześć", "t͡ʂɛɕt͡ɕ"],
    szl: ["serwus", "ˈsɛrvus"],
    uk: ["привіт", "prɪwit"],
    sv: ["hej", "hɛj"],
    no: ["hei", "hɛɪ"],
    da: ["hej", "haj"],
    ro: ["salut", "salut"],
    ga: ["dia duit", "dʲiə dɪtʲ"],
    eu: ["kaixo", "kaiʃo"],
    cy: ["helo", "hɛlo"],
    ka: ["გამარჯობა", "ɡamardʒoba"],
    lzz: ["ბრუნდი", "brundi"],
    sva: ["ხოჩაპ", "xotʃapʰ"],
    laz: ["ხამოს", "xamos"],
    hy: ["բարև", "bɑɾev"],
    hyw: ["բարեւ", "bɑɾev"],
    nv: ["yáʼátʼééh", "jɑ́ːʔɑ́tʰéːh"],
    koy: ["enaa basee'", "enaː baseːʔ"],
    haw: ["aloha", "aloha"],
    mi: ["kia ora", "kia oɾa"],
    qu: ["allillanchu", "aʎiʎantʃu"],
    zh_db: ["你好", "ni˧˩˧xaʊ̯˧˩˧"],
    zh_sc: ["你好", "ni˨˩˧xau˨˩˧"],
    cdo: ["汝好", "ny˧˧ho˧˧"],
    bo: ["བཀྲ་ཤིས་བདེ་ལེགས", "t͡ʂaɕi˥ telek˩˧"],
    bft: ["ཨ་སི་ལམ", "asilam"],
    lbj: ["ཇུ་ལེ", "dʒule"],
    khg: ["ཨ་རོ", "aɾo"],
    cnd: ["nia ja", "nia dʒa"],
    ii: ["ꂿꎆꈐ", "mo˧˧su˧˧kɤ˧˧"],
    azo: ["mosu", "mosu˧˧"],
    hni: ["niahuq mahuq", "niaxuq maxuq"],
    th_isan: ["สะบายดี", "sa˨˩baːj˥diː˥"],
    th_n: ["สวัสดี", "sa˨˩wat˨˩diː˥"],
    th_s: ["สวัสดี", "sa˨˩wat˨˩diː˥"],
    za: ["mwngz ndei", "mɯŋ˧˥dei˥"],
    hmn: ["nyob zoo", "ɲɔ˧˥tɕɔː˥"],
    jv: ["halo", "halo"],
    jvn: ["halo", "halo"],
    su: ["sampurasun", "sampurasun"],
    ceb: ["kumusta", "kumusta"],
    ilo: ["kablaaw", "kablaːw"],
    fj: ["bula", "mbula"],
    rtm: ["noa'ia", "noaʔia"],
    sm: ["talofa", "talofa"],
    to: ["mālō e lelei", "maːloː e lelei"],
    pau: ["alii", "aliː"],
    sd: ["سلام", "sælɑːm"],
    pa: ["ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ", "sət sɾiː əkɑːl"],
    pnb: ["اسلام علیکم", "əsːəlɑːmu ʕəleːkʊm"],
    ne: ["नमस्ते", "nəməste"],
    dty: ["नमस्कार", "nəməskaːɾ"],
    kfx: ["राम राम", "ɾaːm ɾaːm"],
    mr: ["नमस्कार", "nəməskaːɾ"],
    lmn: ["राम राम", "ɾaːm ɾaːm"],
    gu: ["નમસ્તે", "nəməste"],
    si: ["ආයුබෝවන්", "aːjuboːʋən"],
    dv: ["އައްސަލާމް ޢަލައިކުމް", "assalaːmu ʕalaikum"],
    te: ["నమస్కారం", "nəməskaːɾəm"],
    kn: ["ನಮಸ್ಕಾರ", "nəməskaːɾə"],
    ml: ["നമസ്കാരം", "nəməskaːɾəm"],
    tg: ["салом", "sɒlom"],
    ku: ["silav", "sɪlɑːv"],
    ckb: ["سڵاو", "sɬɑːw"],
    sdh: ["سڵاو", "sɫɑːw"],
    ps: ["سلام", "sɑlɑːm"],
    az: ["salam", "sɑlɑːm"],
    azb: ["سلام", "sælam"],
    gag: ["selam", "seˈlam"],
    ug: ["ئەسسالامۇ ئەلەيكۇم", "ɛssɑlɑmu ɛlɛjkum"],
    kk: ["сәлем", "sælem"],
    ky: ["салам", "sɑlɑm"],
    uz: ["salom", "sɑlɒm"],
    tk: ["salam", "sɑlɑːm"],
    mn_cn: ["ᠰᠠᠢᠨ ᠪᠠᠢᠨ᠎ᠠ", "sɑin bɑinɑ"],
    mnc: ["ᠰᡳ ᠰᠠᡳᠨ", "si sain"],
    sjo: ["ᠨᡳᠩᡤᡝ ᠰᠠᡳᠨ", "niŋɡe sain"],
    ar_eg: ["أهلاً", "ʔahlan"],
    ar_lev: ["مرحبا", "maɾħaba"],
    ar_gulf: ["هلا", "hala"],
    ar_iq: ["مرحبا", "maɾħaba"],
    ar_ma: ["السلام", "ssalaːm"],
    arq: ["السلام", "ssalam"],
    mey: ["السلام عليكم", "əssalaːm ʕalaykum"],
    ar_tn: ["أسلامة", "ʔasleːma"],
    ar_sd: ["سلام", "salaːm"],
    ti: ["ሰላም", "sɛlaːm"],
    mt: ["merħba", "mɛɾħba"],
    ig: ["nnọọ", "nːɔː"],
    bom: ["kèèlé", "keːle"],
    tiv: ["m sugh", "m suɣ"],
    efi: ["mọñọ", "mɔɲɔ"],
    ekp: ["nno", "nːo"],
    izi: ["ndo", "ndo"],
    ibb: ["mesiere", "mesiere"],
    urh: ["migwo", "miɡwo"],
    dge: ["amọn", "amɔn"],
    ets: ["udze", "udze"],
    iso: ["mavọ", "mavɔ"],
    ha: ["sannu", "sanːu"],
    xed: ["ʔaza", "ʔaza"],
    ker: ["ásālāmā", "asaːlaːmaː"],
    dbq: ["salaŋ", "salaŋ"],
    wo: ["na nga def", "na ŋɡa dɛf"],
    srr: ["na nga def", "na ŋɡa dɛf"],
    so: ["salaan", "salaːn"],
    om: ["akkam", "akːam"],
    kxc: ["akkam", "akːam"],
    drs: ["mooye", "moːje"],
    dsh: ["nagaya", "naɡaja"],
    rw: ["muraho", "muɾaːho"],
    rn: ["amahoro", "amahoɾo"],
    xh: ["molo", "molo"],
    sn: ["mhoro", "mhoɾo"],
    mxc: ["makadii", "makadiː"],
    ln: ["mbóte", "mbote"],
    ny: ["moni", "moni"],
    yao: ["salama", "salama"],
    en_aave: ["what's up", "wʌts ʌp"],
    en_nz: ["kia ora", "kiə ɔːɾə"],
    en_au: ["g'day", "ɡədæɪ"],
    sco: ["hullo", "hʌlo"],
    af: ["hallo", "ɦaləu"],
    de_gsw: ["Grüezi", "ɡryːətsi"],
    de_at: ["Servus", "zɛɐvʊs"],
    de_by: ["Griaß God", "ɡʁiɐs ɡɔd"],
    gsw: ["Grüezi", "ɡryə̯tsi"],
    swg: ["Grüß Gott", "ɡryːs ɡɔt"],
    bar: ["Servus", "sɛɐvʊs"],
    vmf: ["Grüß Gott", "ɡrʏs ɡɔt"],
    wae: ["Grüössi", "ɡryə̯sːi"],
    nds: ["Moin", "mɔɪn"],
    ksh: ["Tach", "tax"],
    pdc: ["Hallo", "haloː"],
    pdt: ["Goondach", "ɡoːndax"],
    yi: ["שלום עליכם", "ʃɔləm alɛɪxəm"],
    is: ["halló", "halouː"],
    gd: ["halò", "haloː"],
    br: ["demat", "deːmat"],
    nap: ["uè", "wɛ"],
    scn: ["salutamu", "salutamu"],
    vec: ["ciao", "tʃao"],
    co: ["salute", "salute"],
    lij: ["ciâo", "tʃaː"],
    rgn: ["ciô", "ˈtʃoː"],
    egl: ["cciô", "ˈtʃoː"],
    frp: ["adiô", "adjo"],
    ca: ["hola", "ɔlə"],
    gl: ["ola", "ɔla"],
    oc: ["adieu", "adjew"],
    be: ["прывітанне", "prɨvitanʲe"],
    cs: ["ahoj", "aɦoj"],
    sk: ["ahoj", "aɦoj"],
    sl: ["živjo", "ʒiːʋjo"],
    sr: ["здраво", "zdraʋo"],
    bg: ["здравей", "zdravɛj"],
    lt: ["labas", "lɐːbɐs"],
    sgs: ["labs", "labs"],
    lv: ["sveiki", "svɛiki"],
    prg: ["kaīls", "kaiːls"],
    sq: ["përshëndetje", "pəɾʃəndɛtjɛ"],
    aae: ["kalemera", "kalɛmɛɾa"],
    et: ["tere", "tere"],
    ht: ["bonjou", "bɔ̃ʒu"],
    jam: ["wah gwaan", "wɑ ɡwɑːn"],
    bah: ["wuhz hapnin", "wʊz hapnɪn"],
    bzj: ["heloh", "hɛloʊ"],
    pap: ["bon dia", "bon dia"],
    kea: ["ola", "ɔla"],
    rom: ["lačho dives", "latʃʰo divɛs"],
    rmy: ["t’aves baxtalo", "tʼaves baxtalo"],
    rmf: ["šukar diives", "ʃukaɾ diːves"],
    pcm: ["how far", "haʊ faː"],
    tpi: ["halo", "halo"],
    ho: ["kekehe", "kekehe"],
    kmh: ["ñn", "ɲən"],
    nej: ["—", "—"],
    kmu: ["naipa", "naipa"],
    emi: ["emua", "emua"],
    hot: ["kaye", "kaje"],
    fai: ["ben kaba", "ben kaba"],
    nlc: ["silok", "silok"],
    bzh: ["miig", "miːɡ"],
    tcs: ["ai go yu", "aj ɡo ju"],
    pis: ["halo", "halo"],
    hwc: ["howzit", "haʊzɪt"],
    se: ["bures", "pures"],
    sma: ["buerie biejjie", "puerie pie̯jːie"],
    smj: ["buoris", "puɔris"],
    smn: ["tiervâ", "tiervaː"],
    sms: ["tiõrv", "tiɵrv"],
    sjd: ["тиерв", "tjerv"],
    vro: ["tere", "tere"],
    gn: ["mba'éichapa", "mbaʔeitʃapa"],
    yrl: ["poranga", "poɾaŋɡa"],
    chr: ["ᎣᏏᏲ", "osijo"],
    cay: ["sgë:nǫʼ", "skẽːnõʔ"],
    onn: ["sgë:nǫʼ", "skẽːnõʔ"],
    tus: ["skę:nu", "skɛ̃ːnu"],
    as: ["নমস্কাৰ", "nɔmɔxkaɹ"],
    or: ["ନମସ୍କାର", "nɔmɔskaːɾɔ"],
    bho: ["प्रणाम", "pɾəɳaːm"],
    en_south: ["howdy", "haʊdi"],
    en_app: ["howdy", "haːdi"],
    en_in: ["hello", "hɛloː"],
    en_ie: ["hello", "hɛloː"],
    en_sco: ["hello", "hɛlo"],
    en_yk: ["ey up", "eɪ ʊp"],
    en_ck: ["oi", "oɪ"],
    en_sg: ["hello lah", "hɛlo lɑː"],
    fy: ["hoi", "hɔi"],
    frr: ["moin", "mɔin"],
    li: ["hallo", "halo"],
    nn: ["hei", "hæɪ"],
    fo: ["hey", "hɛi"],
    fr_qc: ["allô", "alo"],
    fr_af: ["bonjour", "bɔ̃ʒuʁ"],
    fr_be: ["bonjour", "bɔ̃ʒuʁ"],
    fr_ch: ["bonjour", "bɔ̃ʒuʁ"],
    es_co: ["hola", "ola"],
    es_cl: ["hola", "ola"],
    es_ar: ["hola", "ola"],
    es_cu: ["hola", "ola"],
    es_pe: ["hola", "ola"],
    es_an: ["hola", "ola"],
    lad: ["shalom", "ʃalom"],
    rm: ["allegra", "aleɡra"],
    sc: ["salude", "salude"],
    iu: ["ᐊᐃ", "aj"],
    la: ["salvē", "salweː"],
    el_grc: ["χαῖρε", "kʰâire"],
    el_kath: ["χαίρετε", "ˈçerete"],
    egy: ["𓇋𓈖𓂧𓉔𓂋𓎡", "jined-ħeɾek"],
    en_ang: ["hāl", "hɑːl"],
    enm: ["hail", "hɛːl"],
    en_em: ["good den", "ɡuːd dɛn"],
    ang: ["wes hāl", "wes haːl"],
    ofs: ["heil", "heil"],
    non: ["heill", "hɛilː"],
    got: ["𐌷𐌰𐌹𐌻𐍃", "hɛːls"],
    cu: ["радоуисѧ", "rɑdujisẽ"],
    pi: ["नमो", "namo"],
    pi_edu: ["namo", "namo"],
    pmh: ["—", "—"],
    cop: ["ⲛⲟⲩϥⲣⲓ", "nufri"],
    arc: ["ܫܠܡܐ", "ʃlaːmaː"],
    amw: ["ܫܠܡܐ", "ʃlomaː"],
    aii: ["ܫܠܡܐ", "ʃlaːma"],
    tsm: ["ܫܠܡܐ", "ʃlomo"],
    sux: ["𒁲", "silim"],
    akk: ["𒁲", "ʃulmu"],
    hit: ["—", "—"],
    nci: ["niltze", "niltse"],
    nhx: ["niltze", "niltse"],
    nch: ["niltze", "niltse"],
    nhw: ["niltze", "niltse"],
    nhe: ["nimitzpaca", "nimitspaka"],
    hch: ["kekuanenki", "kekwanenki"],
    ngu: ["niltze", "niltse"],
    ppl: ["ne pakua", "ne pakwa"],
    crn: ["ke'kuanenki", "keʔkwanenki"],
    myn: ["bix a beel", "biʃ a beːl"],
    ine: ["—", "—"],
    zh_song: ["萬福", "wan˥˩fu˧˥"],
    zh_wenyan_edu: ["萬福", "man˨ fʊk˥"],
    zh_han: ["萬福", "miuɑn piuk"],
    zh_tang: ["萬福", "mʉɐnH piuk"],
    ja_edo: ["御機嫌よう", "ɡokiɡeɴjoː"],
    ja_kanbun: ["拝啓", "haikei"],
    ja_heian: ["あなかしこ", "anakasiko"],
    ja_chu: ["御機嫌よろしう", "ɡokiɡen joroɕiu"],
    pry: ["—", "—"],
    ko_mid: ["안녕ᄒᆞ쇼셔", "annjʌŋ hʌ.sjo.sjʌ"],
    oko: ["—", "—"],
    okg: ["—", "—"],
    ko_gor: ["—", "—"],
    ko_em: ["안녕하시오", "annjʌŋ.ha.si.o"],
    vi_han: ["萬福", "vən˨˩ fuk˨˩"],
    vi_nom: ["吀嘲", "sin tɕaːw"],
    eo: ["saluton", "saluton"],
    vo: ["glidis", "ɡlidis"],
    ina: ["salute", "salute"],
    ia: ["salute", "salute"],
    tok: ["toki", "toki"],
    tlh: ["nuqneH", "nuqʰnex"],
    jbo: ["coi", "ʃoj"],
    cjy: ["你好", "ni˨˩˧xau˨˩˧"],
    hsn: ["你好", "n̩˦˩xau˦˩"],
    gan: ["你好", "n̩˨˩hau˨˩˧"],
    mai: ["प्रणाम", "prəɳaːm"],
    anp: ["प्रणाम", "prəɳaːm"],
    awa: ["राम राम", "raːm raːm"],
    thr: ["राम राम", "raːm raːm"],
    bra: ["राधे राधे", "raːdʱe raːdʱe"],
    skr: ["السلام علیکم", "əssəlaːm əleːkum"],
    sat: ["ᱡᱳᱦᱟᱨ", "d͡ʒohar"],
    kru: ["खद्दी", "kʰadːiː"],
    mad: ["salam", "salam"],
    hil: ["kamusta", "kamusta"],
    cbk: ["buenas", "ˈbwenas"],
    bal: ["درود", "dorud"],
    ak: ["akwaaba", "akʷaːba"],
    ada: ["daa", "daː"],
    gaa: ["ɔ jɔ", "ɔ jɔ"],
    nzi: ["akwaaba", "akʷaːba"],
    mk: ["здраво", "ˈzdravɔ"],
    lg: ["oli otya", "oli otja"],
    zne: ["mo ima ya", "mo ima ja"],
    myx: ["mulembe", "mulembe"],
    bxk: ["mulembe", "mulembe"],
    ki: ["wĩmwega", "wimweɡa"],
    mer: ["mwega", "mweɡa"],
    kam: ["mwĩaĩle", "mwiaile"],
    ebu: ["mwega", "mweɡa"],
    tn: ["dumela", "dumeːla"],
    st: ["dumela", "dumɛla"],
    ts: ["avuxeni", "aβuʃeni"],
    ve: ["ndaa", "ndaː"],
    bem: ["muli shani", "muli ʃani"],
    kqn: ["mwapoñai", "mwapoɲai"],
    lua: ["moyo", "mojo"],
    kg: ["mboté", "mbote"],
    lol: ["losáko", "losáko"],
    tll: ["nyongo", "ɲoŋɡo"],
    ff: ["jam tan", "dʒam tan"],
    bm: ["i ni ce", "i ni tʃe"],
    ddn: ["agandɛla", "aɡandɛla"],
    emk: ["i ni se", "i ni se"],
    kao: ["i ni sogoma", "i ni soɡoma"],
    snk: ["an na siri", "an na siɾi"],
    mwk: ["i ni soɣoma", "i ni soɣoma"],
    mlq: ["i ni sögöma", "i ni soɣoma"],
    mev: ["ye", "je"],
    dnj: ["daka", "daka"],
    ses: ["fofo", "fofo"],
    khq: ["fofo", "fofo"],
    dje: ["fofo", "fofo"],
    kab: ["azul", "azul"],
    yua: ["baʼax ka waʼalik", "baʔaʃ ka waʔalik"],
    ncs: ["—", "—"],
    itz: ["b'ix a t'an", "biʃ a tʼan"],
    usp: ["sa'b'al", "saʔbal"],
    tzo: ["kʼusi avokoluk", "kʼusi avokoluk"],
    tzh: ["banti winik", "banti winik"],
    mix: ["nasáa", "nasáː"],
    zap: ["padixhe", "padiʒe"],
    zts: ["padiux", "padiuʃ"],
    maz: ["kjamadhi", "kjamaði"],
    xtm: ["nasáa", "nasáː"],
    mxv: ["sa'a", "saʔa"],
    toc: ["tlen lhítat", "tɬen ɬítat"],
    huv: ["ngwene", "ŋwene"],
    ay: ["kamisaki", "kamisaki"],
    jaq: ["kamishti", "kamiʃti"],
    cni: ["aviro", "aβiɾo"],
    ame: ["salud", "salud"],
    gym: ["käre", "kɨɾe"],
    sum: ["naksa", "naksa"],
    jiv: ["pujamek", "pudʒamek"],
    agr: ["pujámek", "puhámɛk"],
    acu: ["pujamek", "pudʒamek"],
    car: ["mary", "maɾi"],
    pbb: ["mañi", "maɲi"],
    gum: ["ma'rik", "maʔɾik"],
    arn: ["mari mari", "maɾi maɾi"],
    cr: ["ᑕᓂᓯ", "taːnisi"],
    chp: ["edlanetʼè", "eðlanetʼe"],
    oj: ["boozhoo", "boːʒoː"],
    atj: ["kwei", "kwej"],
    mic: ["kwe'", "ɡʷeʔ"],
    pqm: ["kʼulasuwiyat", "kʼulasuwijat"],
    abe: ["kwai", "kwai"],
    umu: ["hé", "heː"],
    crk: ["ᑖᓂᓯ", "taːnisi"],
    yur: ["aiy-yue-kwee", "aj-juːkweː"],
    lkt: ["háu", "háu"],
    kl: ["aluu", "aluː"],
    ce: ["маршалла", "maɾʃalːa"],
    inh: ["моаршал", "moaɾʃal"],
    av: ["ворчӏами", "voɾtʃʼami"],
    lez: ["салам", "salam"],
    dar: ["салам", "salam"],
    agx: ["салам", "salam"],
    ddo: ["салам", "salam"],
    lbe: ["салам", "salam"],
    tab: ["салам", "salam"],
    aqc: ["аᴉмбᴉр", "ambiɾ"],
    udi: ["салам", "salam"],
    tkr: ["салам", "salam"],
    kum: ["ассаламу алейкум", "asːalamu alejkum"],
    nog: ["ассаламу алейкум", "asːalamu alejkum"],
    ady: ["шӏуфес", "ʃʼwafes"],
    kbd: ["фӏэхъус", "fʼaqʷəs"],
    ab: ["мшыбзиа", "mʃəbzia"],
    abq: ["мшыбзи", "mʃəbzi"],
    uby: ["—", "—"],
    xmf: ["გეგაჯანას", "ɡeɡadʒanas"],
    os: ["салам", "salam"],
    ty: ["'ia ora na", "ʔia oɾa na"],
    niu: ["fakaalofa atu", "fakaalofa atu"],
    tvl: ["taalofa", "taːlofa"],
    rap: ["'iorana", "ʔioɾana"],
    rar: ["kia orāna", "kia oɾaːna"],
    mh: ["yokwe", "jokwe"],
    gil: ["mauri", "mauɾi"],
    ch: ["håfa adai", "haːfa adai"],
    tet: ["bondia", "bondia"],
    tdt: ["olá", "ola"],
    aoz: ["neut", "neut"],
    bi: ["halo", "halo"],
    pip: ["halo", "halo"],
    pjt: ["palya", "palja"],
    wbp: ["palka", "palka"],
    piu: ["palya", "palja"],
    aer: ["werte", "wɛɾte"],
    nha: ["palya", "paʎa"],
    olg: ["palya", "paʎa"],
    adt: ["palya", "paʎa"],
    nys: ["kaya", "kaja"],
    xul: ["yumalundi", "jumalundi"],
    wbt: ["palya", "paʎa"],
    mni: ["ꯈꯨꯔꯨꯝꯖꯔꯤ", "kʰuɾumdʒaɾi"],
    bpy: ["নমস্কার", "nomoskar"],
    new: ["ज्वजलपा", "dʒwadʒalpa"],
    lif: ["ᤐᤣᤜᤢᤙᤣ", "peːhuːje"],
    tdh: ["नमस्ते", "nəməste"],
    brx: ["खुशी", "kʰuʃi"],
    adi: ["nasi sukna", "nasi sukna"],
    nag: ["namaskar", "namaskaɾ"],
    nzm: ["hangba", "haŋba"],
    nmf: ["hayau", "hajau"],
    lus: ["chibai", "tʃibai"],
    dz: ["ཀུ་ཟུ་ཟངས་པོ་ལ", "kuzu zaŋpo la"],
    xsr: ["ཏ་ཤེས་ཏེ་ལེ", "tashi dele"],
    xkz: ["kuzu zangpo", "kuzu zaŋpo"],
    sik: ["ཁམས་བཟང", "kʰamsaŋ"],
    min: ["salam", "salam"],
    nia: ["ya'ahowu", "jaʔahowu"],
    ban: ["om swastiastu", "om swastiastu"],
    ace: ["assalamualaikum", "assalamualaikum"],
    gay: ["salam", "salam"],
    bug: ["—", "—"],
    mdr: ["salama' ma'ondong", "salamaʔ maʔondoŋ"],
    war: ["maupay nga aga", "maʔupaj ŋa aɡa"],
    bik: ["maugmang aga", "maʔuɡmaŋ aɡa"],
    bto: ["marhəy na ag-ərahn", "maɾhəj na aɡʔəɾahn"],
    tum: ["monire", "moniɾe"],
    kde: ["nakushukuru", "nakuʃukuɾu"],
    seh: ["mwadzukabwanji", "mwadzukabwandʒi"],
    ngl: ["salama", "salama"],
    din: ["ke yïn", "ke jin"],
    nus: ["malɛ", "malɛ"],
    anu: ["mali", "mali"],
    luo: ["misawa", "misawa"],
    mas: ["sopa", "sopa"],
    aue: ["ǂòwo", "ǂòwo"],
    bfa: ["gwon", "ɡwon"],
    saq: ["sopa", "sopa"],
    aa: ["nagá", "naɡa"],
    shi: ["azul", "azul"],
    rif: ["azul", "azul"],
    shy: ["azul", "azul"],
    mwr: ["खम्मा घणी", "kʰəmːaː ɡʱəɳiː"],
    bgc: ["राम राम", "ɾaːm ɾaːm"],
    ks: ["اسلام علیکم", "assalaːmu ʕalaikum"],
    kok: ["नमस्कार", "nəməskaːɾ"],
    mnp: ["你好", "ny˧˧hau˧˧"],
    nan_te: ["汝好", "lɯ˥˧ho˥˧"],
    yue_ts: ["你好", "nei˧˧hau˧˧"],
    czh: ["你好", "n˦˦hau˦˦"],
    cnp: ["你好", "nei˦˨hou˦˨"],
    zh_jh: ["你好", "ni˨˩˦xau˨˩˦"],
    zh_tj: ["你好", "ni˨˩˧xau˨˩˧"],
    zh_lz: ["你好", "ni˥˧xau˥˧"],
    dng: ["ни хау", "ni xau"],
    hsb: ["witaj", "ˈvitaj"],
    csb: ["witôj", "ˈvitwɔj"],
    rue: ["Слава Ісусу Христу", "ˈslava ˈjisusu ˈxristu"],
    fur: ["mandi", "ˈmandi"],
    ast: ["hola", "ˈola"],
    ext: ["salú", "saˈlu"],
    fla: ["salú", "saˈlu"],
    an: ["hola", "ˈola"],
    rup: ["bunâ-vã ziuâ", "ˈbunɨ vɨ ˈziwɨ"],
    ruq: ["ubavu", "uˈbavu"],
    wa: ["bondjoû", "bõˈd͡ʒu"],
    kpv: ["видза олан", "vidza olan"],
    koi: ["бур лун", "bur lun"],
    udm: ["ӟечбур", "dʑetɕbur"],
    mhr: ["салам лийже", "salam lijʒe"],
    mrj: ["пӓрӓнӓ", "pæræ næ"],
    myv: ["шумбрат", "ʃumbrat"],
    mdf: ["шумбрат", "ʃumbrat"],
    krl: ["terveh", "ˈterveh"],
    olo: ["terveh", "ˈterveh"],
    vep: ["tervhen", "ˈtervhen"],
    vot: ["tervetä", "ˈtervetæ"],
    liv: ["tervīst", "tɛrviːst"],
    mzn: ["سلام", "sælɒːm"],
    glk: ["سلام", "sælɒːm"],
    lrc: ["سلام", "sælɒːm"],
    crh: ["selâm", "selæm"],
    tt: ["исәнмесез", "isænmesez"],
    ba: ["һаумыһығыҙ", "hawmɯhɯɣɯð"],
    krc: ["салам", "salam"],
    ksw: ["ဘၣ်တၢ်ဆၢ", "baŋ ta sa"],
    pwo: ["ဂ့ၤထီၣ်", "ɣɛ tʰi"],
    lhu: ["ô-bo-haˇ", "óbohâʔ"],
    lis: ["ngo-lan", "ŋolan"],
    nxq: ["nyel-bbeq", "ɲɯ˥bɯ˨˩"],
    shn: ["မႂ်ႇသုင်", "maj suŋ"],
    jia: ["niː", "niː"],
    kbp: ["ndɩ na", "ndɩ na"],
    ee: ["ŋdi", "ŋdi"],
    gej: ["ado", "ado"],
    aja: ["nɛnɛ", "nɛnɛ"],
    nyn: ["agandi", "aɡandi"],
    cgg: ["oraire", "oraire"],
    ttj: ["oraire ota", "oraire ota"],
    nyo: ["oraire ota", "oraire ota"],
    luy: ["mulembe", "mulembe"],
    ssw: ["sawubona", "sawuɓona"],
    nbl: ["lotjhani", "lotʃʰani"],
    nd: ["salibonani", "saliɓonani"],
    nso: ["dumela", "dumɛla"],
    fan: ["mbolo", "mbolo"],
    naq: ["matisâ", "matisaː"],
    hts: ["ʼmtana", "ʔmtana"],
    nmn: ["—", "—"],
    kr: ["lafiya", "lafija"],
    men: ["bua", "bua"],
    vai: ["ꕒꔢ", "famo"],
    tem: ["seke", "seke"],
    dyu: ["i ni soɣoma", "i ni soɣoma"],
    bbo: ["ka kɛ", "ka kɛ"],
    spp: ["mɛ", "mɛ"],
    sus: ["inu uxara", "inu uxaɾa"],
    syl: ["আদাব", "adab"],
    rhg: ["assalam", "assalam"],
    ctg: ["আদাব", "adab"],
    mag: ["परणाम", "prəɳaːm"],
    doi: ["नमस्कार", "nəməskaːr"],
    xkk: ["lɔh", "lɔh"],
    moh: ["she:kon", "ʃekon"],
    cho: ["halito", "halito"],
    mus: ["hensci", "hinsdʒi"],
    esu: ["waqaa", "waqaː"],
    ipk: ["paglagvik", "paɡlaɡvik"],
    ess: ["аипак", "aipak"],
    ale: ["аӈ", "aŋ"],
    apw: ["dahgotʼe", "dahɡotʔe"],
    dak: ["háu", "háu"],
    chy: ["Haaahe", "haːhe"],
    arp: ["héébe", "héːbe"],
    kio: ["hâ:tô:", "hâːtôː"],
    lmo: ["ciao", "ˈtʃaːo"],
    pms: ["ciao", "tʃao"],
    eml: ["ciao", "ˈtʃao"],
    mwl: ["olá", "oˈla"],
    pnt: ["καλημέρα", "kaliˈmera"],
    hno: ["اسلام علیکم", "assalaːmu ʕalaikum"],
    bhb: ["राम राम", "raːm raːm"],
    cja: ["salam", "salam"],
    hmo: ["oi e namo", "oi e namo"],
    meu: ["namo", "namo"],
    pon: ["kaselehlie", "kaselehlie"],
    kos: ["lwen wo", "lwen wo"],
    myz: ["ࡔࡋࡀࡌࡀ", "ʃlama"],
    vmw: ["salaama", "salaːma"],
    dsb: ["witaj", "ˈvitaj"],
    gv: ["moghrey mie", "ˈmɔɣrə maː"],
    kw: ["dydh da", "dɪð daː"],
    zza: ["silam", "silam"],
    brh: ["سلام", "sælaːm"],
    mrq: ["kaoha", "kaoha"],
    tiw: ["ngirramini", "ŋiɾamini"],
    lbz: ["—", "—"],
    lbz_damin: ["—", "—"],
    nny: ["—", "—"],
    kky: ["—", "—"],
    guc: ["jamaya", "xamaja"],
    mch: ["etämä", "etɨmɨ"],
    wba: ["yakera", "jakeɾa"],
    mzh: ["hayej", "hajex"],
    myp: ["gaíhií", "ɡaíhií"],
    tue: ["—", "—"],
    emp: ["sake bia", "sake bia"],
    kpe: ["halee", "haleː"],
    bsq: ["nyɔɔnpe", "ɲɔːnpe"],
    loz: ["eni sha", "ɛni ʃa"],
    bbc: ["horas", "horas"],
    bts: ["horas", "horas"],
    akb: ["horas", "horas"],
    bjn: ["salam", "salam"],
    abs: ["hela", "hela"],
    max: ["cerang", "tʃeraŋ"],
    mui: ["halo", "halo"],
    sas: ["salam", "salam"],
    kha: ["khublei", "kʰublei"],
    mns: ["пася", "pasja"],
    mrw: ["kapian", "kapijan"],
    tsg: ["kumusta", "kumusta"],
    yap: ["mogethin", "moɡetʰin"],
    chk: ["ráán annim", "raːn annim"],
    gbm: ["राम राम", "raːm raːm"],
    kfy: ["ज्यू नमस्कार", "dʒjuː nəməskaːr"],
    xnr: ["नमस्कार", "nəməskaːr"],
    hr: ["bok", "bok"],
    bs: ["zdravo", "ˈzdravo"],
    iba: ["salam", "salam"],
    ljp: ["tabik", "tabik"],
    tzm: ["azul", "azul"],
    tmh: ["ma toleɣ", "ma toləɣ"],
    ng: ["wa lalapo", "wa lalapo"],
    kj: ["wa hala po", "wa hala po"],
    umb: ["oloi", "oloi"],
    kmb: ["kiebi", "kiebi"],
    lue: ["mwane", "mwane"],
    her: ["wa penduka", "wa penduka"],
    xal: ["менд", "mend"],
    sg: ["bara mo", "bara mo"],
    toi: ["mwabuka buti", "mwabuka buti"],
    peo: ["—", "—"],
    ave: ["—", "—"],
    xto: ["—", "—"],
    txb: ["—", "—"],
    phn: ["𐤔𐤋𐤌", "ʃalom"],
    uga: ["𐎌𐎍𐎎", "ʃalaːmu"],
    xlu: ["—", "—"],
    pal: ["𐭣𐭫𐭥𐭲", "droːd"],
    fa_clas: ["درود", "duruːd"],
    syc: ["ܫܠܡܐ", "ʃlaːmaː"],
    fro: ["salut", "saˈlyt"],
    fr_class: ["Dieu vous garde", "djø vu ɡard"],
    it_dan: ["salute", "saˈlute"],
    goh: ["heil", "heil"],
    gez: ["ሰላም", "salaːm"],
    gmy: ["—", "—"],
    xct_litpr: ["བཀྲ་ཤིས་བདེ་ལེགས", "tʂaʃi delek"],
    xct: ["བཀྲ་ཤིས་བདེ་ལེགས", "tʂaʃi deleks"],
    xpu: ["𐤔𐤋𐤌", "ʃalom"],
    xhu: ["𒄭𒇻", "hilːu"],
    elx: ["𒅆𒅋𒄩", "ʃilha"],
    xsa: ["𐩪𐩡𐩣", "salaːm"],
    kaw: ["ꦫꦲꦪꦸ", "rahaju"],
    kho: ["𑀤𑁆𑀭𑀽𑀤𑀻", "drːuːdiː"],
    de_lut: ["Gott zum Gruß", "ɡɔt tsʊm ɡruːs"],
    gmh: ["gegrüezet", "ɡəˈɡryːətsət"],
    es_sgl: ["Dios os guarde", "djos os ˈɡwaɾde"],
    osp: ["salud", "saˈlud"],
    okz: ["សួស្តី", "suəsdəj"],
    osx: ["heil", "heil"],
    smg: ["mbinhi", "mbiɲi"],
    mos: ["ne y yibeoogo", "ne i jibeoɡo"],
    maw: ["n na ti bʋɔ", "n na ti bʊɔ"],
    kln: ["chamege", "tʃameɡe"],
    mfe: ["bonzour", "bõzuɾ"],
    rcf: ["bonzour", "bõzuʁ"],
    crs: ["bonzour", "bõzuʁ"],
    gcf: ["bonjou", "bõʒu"],
    mnk: ["salaam", "salaːm"],
    bqi: ["سلام", "salaːm"],
    unr: ["johar", "dʒohar"],
    hoc: ["johar", "dʒohar"],
    enq: ["baa wa", "baː wa"],
    xpr: ["drōd", "droːd"],
    xqa: ["salām", "salaːm"],
    sga: ["—", "—"],
    bsk: ["šuá", "ʂuaː"],
    yag: ["салом", "salom"],
    srn: ["odi", "odi"],
    djk: ["fa yu de", "fa ju de"],
    srm: ["kɔlɔkɔlɔ", "kɔlɔkɔlɔ"],
    kwk: ["gilakas'la", "ɡilakasla"],
    blc: ["—", "—"],
    sad: ["gabaeesa", "ɡabaeːsa"],
    pcc: ["meez ndil", "meː˩˩ ndi˧˥"],
    iuu: ["yiem-longx", "jiem˧loŋ˨˧"],
    hui: ["balu", "balu"],
    tkl: ["malo ni", "malo ni"],
    squ: ["chen kwenmántumi", "tʃen kʷenmantumi"],
    mga: ["—", "—"],
    hbo: ["שלום", "ʃaːloːm"],
    he_mis: ["שלום", "ʃɑlom"],
    hy_grab: ["ողջոյն", "oɣdʒujn"],
    mpt: ["aben", "aben"],
    ygr: ["amige", "amiɡe"],
    roo: ["ega", "eɡa"],
    quz: ["rimaykullayki", "rimajkuʎajki"],
    quy: ["napaykullayki", "napajkuʎajki"],
    shp: ["jakon raoma", "xakon raoma"],
    cab: ["mabuiga", "mabuiɡa"],
    crx: ["ʼahdoozaee", "ʔahdoːzaː"],
    tsi: ["ndii ne", "ndiː ne"],
    thp: ["weytk", "wejtk"],
    wbl: ["салам", "salam"],
    psi: ["سلام", "salaːm"],
    bgq: ["खम्मा घणी", "kʰəmːaː ɡʱəɳiː"],
    laj: ["itye nining", "itje niniŋ"],
    ach: ["itye nining", "itje niniŋ"],
    rki: ["မဂႝလာပါ", "mìɴɡəlà pà"],
    cnh: ["na dam maw", "na dam maw"],
    kxm: ["សួស្តី", "suːəsdəj"],
    xng: ["ᠠᠮᠤᠷ", "amur"],
    ja_kg: ["おやっとさあ", "ojattosaː"],
    ja_sd: ["こんぬづは", "konnɯdzɯwa"],
    ko_hg: ["안녕하시꼬마", "annjʌŋhaɕikːoma"],
    ko_jl: ["안녕하쇼", "annjʌŋhaɕjo"],
    nan_pn: ["你好", "li˥˧ho˥˧"],
    mra: ["hahɔ", "haho"],
    wuu_nb: ["侬好", "noŋ˦˦hɔ˨˩˦"],
    yue_gz: ["你好", "nei˧˥hɔu˧˥"],
    khb: ["ᦷᦡᧃᦟᦲ", "dɔn liː"],
    blt: ["ꪎꪺꪎꪒꪲ", "sa wad dii"],
    pam: ["kumusta", "kuˈmusta"],
    pag: ["maabig ya agew", "maˈʔabiɡ ja ˈʔaɡew"],
    mdh: ["assalamu alaikum", "assaˈlamu ʔaˈlajkum"],
    gor: ["assalamu alaikum", "assaˈlamu ʔaˈlajkum"],
    mak: ["salama'", "saˈlamaʔ"],
    fon: ["a fɔn ganji", "a fɔ̃ ɡãdʒi"],
    kri: ["kushɛ", "kuˈʃɛ"],
    dag: ["dasiba", "dasiba"],
    xog: ["mwaakire", "mwaːkiɾe"],
    teo: ["yoga", "joɡa"],
    dyo: ["kasumay", "kasumaj"],
    bci: ["akwaba", "akwaba"],
    tcy: ["ನಮಸ್ಕಾರ", "namaskaːɾa"],
    haz: ["سلام", "salom"],
    tly: ["xəyrli ruj", "xəjɾli ɾuʒ"],
    kaa: ["salam", "salam"],
    bej: ["salaam", "salaːm"],
    tig: ["ሰላም", "salaːm"],
    byn: ["ኢራዋ", "irawa"],
    ssy: ["malaal", "malaːl"],
    ewo: ["mbɔlɔ", "mbɔlɔ"],
    bum: ["mbolo", "mbolo"],
    agq: ["kâa'", "kaːʔ"],
    mgo: ["mɔlɔŋ", "mɔlɔŋ"],
    dur: ["mbóò", "mboo"],
    ndc: ["mhoroi", "mhoɾoji"],
    ote: ["hatsi", "hatsi"],
    otq: ["hä", "hã"],
    tar: ["kuira", "kuiɾa"],
    orv: ["здравъ", "zdravŭ"],
    xsc: ["—", "—"],
    sukh: ["—", "—"],
    xmr: ["—", "—"],
    onw: ["ⲉⲓⲗⲗⲉ", "ille"],
    cqu: ["rimaykullayki", "rimajkuʎajki"],
    omc: ["—", "—"],
    chb: ["chibu", "tʃibu"],
    oma: ["—", "—"],
    osu: ["wilujeng", "wiludʒəŋ"],
    otl: ["ᜋᜊᜓᜑᜌ᜔", "mabuhaj"],
    zkt: ["—", "—"],
    juc: ["—", "—"],
    omx: ["—", "—"],
    pyx: ["—", "—"],
    obr: ["—", "—"],
    occ: ["—", "—"],
    och: ["—", "—"],
    ojp: ["—", "—"],
    pjk: ["—", "—"],
    vsa: ["स्वस्ति", "swasti"],
    txg: ["—", "—"],
    sog: ["drwd", "druːd"],
    otk: ["—", "—"],
    ami: ["nga'ay ho", "ŋaʔai ho"],
    pwn: ["masalu", "masalu"],
    tay: ["lokah", "lokah"],
    bnn: ["uninang", "uninaŋ"],
    trv: ["malu", "malu"],
    tsu: ["yokeoasu", "jokeoasu"],
    tao: ["akokay", "akokai"],
    pyu: ["marayas", "maɾajas"],
    szy: ["marayas", "maɾajas"],
    ssf: ["ya", "ja"],
    hak_tw: ["你好", "ŋi˩˩ ho˧˩"],
    wuu_sz: ["你好", "ne˨˧ɦɔ˥˨"],
    wuu_wz: ["你好", "ŋ˧˩hau˧˥"],
    nan_qz: ["汝好", "li˧˥ho˧˥"],
    nan_hai: ["汝好", "li˨˩˧ho˨˩˧"],
    zh_wh: ["你好", "ni˨˩˧xau˨˩˧"],
    zh_zz: ["你好", "ni˥˥xau˥˥"],
    hak_hl: ["你好", "ŋi˨˦ho˨˦"],
    cpx: ["你好", "ni˦˩ho˦˩"],
    mfa: ["nyaman ka", "ɲaman ka"],
    mtq: ["đám rộ", "ɗaːm roː"],
    tyz: ["chào", "tʃaːw˨˩"],
    kjp: ["နာမှၤ", "na˧ʃi˧"],
    kac: ["kaja i", "kadʒa˧i˧"],
    wbm: ["sao", "sao"],
    pll: ["vaː piə", "vaː piə"],
    ahk: ["u du la", "u˧du˧la˧"],
    dtp: ["kopivosian", "kopivosian"],
    hne: ["जोहार", "dʒoːɦaːr"],
    mnw: ["ပ္ဍဲဂေါဝ်", "ɓɔŋ kaow"],
    bru: ["te", "te"],
    bdq: ["ô", "o"],
    lwl: ["lavüa", "lavɨa"],
    grt: ["namaste", "namaste"],
    nut: ["choà", "tʃɔaː˨˩"],
    quc: ["saqarik", "saqaɾik"],
    cak: ["utz iwäch", "uts iwætʃ"],
    kek: ["ma saʼ laachʼool", "ma sa laːtʃʼoːl"],
    poh: ["ma chaa", "ma tʃaː"],
    kjb: ["kawal", "kawal"],
    ctu: ["kabʼ", "kabʼ"],
    toj: ["lekiluk'", "lekilukʼ"],
    bzd: ["iri'", "iɾiʔ"],
    cuk: ["nuedi", "nweðiː"],
    chf: ["bin a bel", "bin a bel"],
    agu: ["kʼamta", "kʼamta"],
    ixl: ["nima'la kuxhewchʼa", "nimaʔla kuʃewtʃʼa"],
    mam: ["chjonte tey", "tʃhonte tej"],
    mvc: ["chjonte tey", "tʃhonte tej"],
    wal: ["saro", "saro"],
    sid: ["nagaa yi'ne", "naɡaː jiʔne"],
    tji: ["shu shu", "ʃu˧ʃu˧"],
    nij: ["tabea", "tabea"],
    sda: ["tabe", "tabe"],
    lld: ["bun de", "bun de"],
    stq: ["Moin", "moin"],
    wym: ["yti", "ˈytɪ"],
    yuc: ["—", "—"],
    kgg: ["—", "—"],
    ota: ["سلام", "seˈlaːm"],
    cmg: ["ᠰᠠᠶᠢᠨ ᠤᠤ", "sajin uu"],
    ett: ["—", "—"],
    cms: ["—", "—"],
    xht: ["—", "—"],
    txr: ["—", "—"],
  },
};
