/**
 * sun — see docs/words/CONTRIBUTING.md for editing guidance.
 * Language codes: see docs/words/LANG_CODES.md.
 */
WORDS.sun = {
  label: {
    en: "Sun",
    ja: "日",
    ko: "해",
    zh: "太阳",
    yue: "日頭",
    vi: "Mặt trời",
    th: "ดวงอาทิตย์",
    id: "Matahari",
    hi: "सूरज",
    de: "Sonne",
    fr: "Soleil",
    it: "Sole",
    es: "Sol",
    es_eu: "Sol",
    es_mx: "Sol",
    pt: "Sol",
    pt_eu: "Sol",
    pt_br: "Sol",
    ru: "Солнце",
    uk: "Сонце",
    ar: "شمس",
    he: "שמש",
    sw: "Jua",
  },
  definition: {
    en: "The star Sol seen from Earth; \"the sun in the sky\".",
    ja: "地球から見える恒星としての太陽。「空の太陽」。",
    ko: "지구에서 보이는 항성으로서의 해. \"하늘의 해\".",
    zh: "从地球上看到的太阳；\"天上的太阳\"。",
    yue: "由地球望到嘅太陽；「天上嘅太陽」。",
    vi: "Mặt trời nhìn từ Trái Đất; \"mặt trời trên bầu trời\".",
    th: "ดาวฤกษ์ดวงอาทิตย์ที่มองเห็นจากโลก; \"พระอาทิตย์บนฟ้า\"",
    id: "Bintang matahari yang terlihat dari Bumi; \"matahari di langit\".",
    hi: "पृथ्वी से दिखने वाला सूर्य; \"आकाश का सूर्य\"।",
    de: "Die Sonne, gesehen von der Erde aus; \"die Sonne am Himmel\".",
    fr: "Le Soleil vu depuis la Terre; \"le soleil dans le ciel\".",
    it: "Il Sole visto dalla Terra; \"il sole nel cielo\".",
    es: "El Sol visto desde la Tierra; \"el sol en el cielo\".",
    es_eu: "El Sol visto desde la Tierra; \"el sol en el cielo\".",
    es_mx: "El Sol visto desde la Tierra; \"el sol en el cielo\".",
    pt: "O Sol visto da Terra; \"o sol no céu\".",
    pt_eu: "O Sol visto da Terra; \"o sol no céu\".",
    pt_br: "O Sol visto da Terra; \"o sol no céu\".",
    ru: "Солнце, видимое с Земли; \"солнце на небе\".",
    uk: "Сонце, видиме з Землі; \"сонце в небі\".",
    ar: "الشمس كما تُرى من الأرض؛ \"الشمس في السماء\".",
    he: "השמש כפי שהיא נראית מכדור הארץ; \"השמש בשמיים\".",
    sw: "Jua kama linavyoonekana kutoka Dunia; \"jua angani\".",
  },
  data: {
    ja: ["日", "hi"],
    ja_osa: ["日", "hi"],
    ja_aom: ["日", "hi"],
    ja_oki: ["てぃだ", "tida"],
    ja_hak: ["日", "hi"],
    ja_kyo: ["日", "hi"],
    ja_hir: ["日", "hi"],
    ja_mvi: ["てぃだ", "tida"],
    ja_rys: ["てぃだ", "tida"],
    ko: ["해", "hɛ"],
    ko_kp: ["해", "hɛ"],
    ko_bus: ["해", "hɛ"],
    ko_jeju: ["해", "hɛ"],
    ko_yb: ["해", "hɛ"],
    zh: ["太阳", "tʰaɪ̯˥˩jɑŋ˩"],
    yue: ["日頭", "jɐt˨ tʰɐu˨˩"],
    nan: ["日頭", "lit˦˧tʰau˧˥"],
    wuu: ["太阳", "da˩jã˩"],
    hak_cn: ["日头", "ŋit˧tʰeu˧˥"],
    vi: ["mặt trời", "mət˨˩ tɤːj˨˩"],
    vi_c: ["mặt trời", "maːk˨˨ ʈɤːj˧˨"],
    vi_s: ["mặt trời", "mak˨˩˨ tɤːj˨˩"],
    th: ["ดวงอาทิตย์", "duaŋ˧ʔaː˧tʰit˧˥"],
    id: ["matahari", "matahari"],
    ms: ["matahari", "matahari"],
    hi: ["सूरज", "suːɾad͡ʒ"],
    hns: ["suuraj", "suːɾadʒ"],
    sa_edu: ["सूर्यः", "suːɾjaɦ"],
    sa: ["सूर्यः", "suːɾjaɦ"],
    bn: ["সূর্য", "ʃuɾd͡ʒo"],
    rkt: ["সুরুজ", "suɾud͡ʒ"],
    ur: ["سورج", "suːɾad͡ʒ"],
    ta: ["சூரியன்", "suːɾijan"],
    iru: ["čūriyen", "tʃuːɾijen"],
    en: ["sun", "sʌn"],
    de: ["Sonne", "zɔnə"],
    fr: ["soleil", "sɔlɛj"],
    pcd: ["solèl", "sɔlɛl"],
    nrf: ["solé", "sɔle"],
    it: ["sole", "ˈsoːle"],
    es_eu: ["sol", "sol"],
    es_mx: ["sol", "sol"],
    pt_eu: ["sol", "sɔɫ"],
    pt_br: ["sol", "sɔw"],
    ru: ["солнце", "sont͡sɨ"],
    ar_qur: ["شمس", "ʃams"],
    ar: ["شمس", "ʃams"],
    he: ["שמש", "ʃemeʃ"],
    tr: ["güneş", "ɟyneʃ"],
    fa: ["خورشید", "xorʃiːd"],
    jpr: ["חורשיד", "xorʃiːd"],
    prs: ["خورشید", "xoɾʃed"],
    trm: ["suri", "suɾi"],
    sw: ["jua", "dʒua"],
    suk: ["ilyuva", "iʎuβa"],
    nym: ["izuβa", "izuβa"],
    rim: ["nzua", "nzua"],
    ksb: ["zuwa", "zuwa"],
    jmc: ["ìsùwà", "isuwa"],
    sbp: ["liluga", "liluɡa"],
    rwk: ["mlao", "mlao"],
    asu: ["nyu", "ɲu"],
    tl: ["araw", "aɾaw"],
    agt: ["agew", "aɡew"],
    mn: ["нар", "nar"],
    sah: ["күн", "kyn"],
    tyv: ["хүн", "xyn"],
    kjh: ["кӱн", "kyn"],
    alt: ["кӱн", "kyn"],
    cv: ["хӗвел", "xɘvel"],
    bxr: ["наран", "naran"],
    mvf: ["nara", "nara"],
    evn: ["дылача", "dɯlatɕa"],
    eve: ["нөлтэн", "nølten"],
    gld: ["сиун", "siun"],
    ude: ["даигаси", "daiɡasi"],
    yrk: ["хаер", "xajer"],
    enf: ["kayua", "kajua"],
    nio: ["койка", "kojka"],
    sel: ["нэлмо", "nelmo"],
    kca: ["хатәл", "xatəl"],
    ckt: ["тиркытир", "tirkɯtir"],
    kpy: ["тиӈытиӈ", "tiŋɯtiŋ"],
    itl: ["коачʼ", "koatʃʼ"],
    ykg: ["пугэ", "puɣe"],
    yux: ["пугэ", "puɣe"],
    niv: ["керк", "kerk"],
    ket: ["и", "i"],
    my: ["နေ", "nè"],
    km: ["ព្រះអាទិត្យ", "prĕəh ʔaːtɨt"],
    lo: ["ຕາເວັນ", "taː˩˧ ven˩"],
    soa: ["ตะวัน", "ta˩˧ wan˧"],
    yo: ["oòrùn", "oòɾùn"],
    zu: ["ilanga", "ilaŋɡa"],
    am: ["ፀሐይ", "sʼɛhaj"],
    aiw: ["saba", "saba"],
    sgw: ["ፀሐይ", "sʼɛhaj"],
    mg: ["masoandro", "masuandɾu"],
    ain: ["チュプ", "tɕup"],
    fi: ["aurinko", "ɑuɾiŋko"],
    hu: ["nap", "nɒp"],
    ohu: ["nȁp", "nɒp"],
    el: ["ήλιος", "ilios"],
    nl: ["zon", "zɔn"],
    pl: ["słońce", "ˈswɔɲt͡sɛ"],
    szl: ["słōńce", "ˈswɔɲt͡sɛ"],
    uk: ["сонце", "sɔnt͡sɛ"],
    sv: ["sol", "suːl"],
    no: ["sol", "suːl"],
    da: ["sol", "soːˀl"],
    ro: ["soare", "soare"],
    ga: ["grian", "ɡɾʲiən"],
    eu: ["eguzki", "eɡuski"],
    cy: ["haul", "haɨl"],
    ka: ["მზე", "mze"],
    lzz: ["ბჟა", "bʒa"],
    sva: ["მიჟ", "miʒ"],
    laz: ["მჟორა", "mʒora"],
    hy: ["արև", "ɑˈɾev"],
    hyw: ["արեւ", "ɑˈɾev"],
    nv: ["jóhonaaʼéí", "dʒóhonɑːʔéːí"],
    koy: ["so", "so"],
    haw: ["lā", "laː"],
    mi: ["rā", "ɾaː"],
    qu: ["inti", "inti"],
    zh_db: ["太阳", "tʰaɪ̯˥˩jɑŋ˩"],
    zh_sc: ["太阳", "tʰai˥˩iaŋ˧˥"],
    cdo: ["日头", "nit˧˧tʰau˧˧"],
    bo: ["ཉི་མ", "ɲima˩˧"],
    bft: ["ཉི་མ", "ɲima"],
    lbj: ["ཉི་མ", "ɲima"],
    khg: ["ཉི་མ", "ɲima"],
    cnd: ["mu", "mu"],
    ii: ["ꉢꁡ", "ȵi˧˧mo˧˧"],
    azo: ["ŋᴊni", "ŋnʲi˧˧"],
    hni: ["mol", "mol"],
    th_isan: ["ตะเว็น", "ta˨˩wen˥"],
    th_n: ["ตะวัน", "ta˨˩wan˥"],
    th_s: ["ตะวัน", "ta˨˩wan˥"],
    za: {
      form: "日",
      ipa:  "taːŋ˧˥ŋɯn˧˥",
      alt: [
        { form: "daengzngoenz", script: "Latin (Sawcuengh)", source: "1957/1982 official orthography" },
      ],
    },
    hmn: ["hnub", "nu˧˥"],
    jv: ["srengéngé", "srəŋeŋe"],
    jvn: ["srengéngé", "srəŋeŋe"],
    su: ["panonpoé", "panɔnpoe"],
    ceb: ["adlaw", "adlaw"],
    ilo: ["init", "init"],
    fj: ["siga", "siŋa"],
    rtm: ["asa", "asa"],
    sm: ["lā", "laː"],
    to: ["laʻā", "laʔaː"],
    pau: ["sils", "sils"],
    sd: ["سج", "sʊdʒə"],
    pa: ["ਸੂਰਜ", "suːɾədʒ"],
    pnb: ["سورج", "suːɾədʒ"],
    ne: ["सूर्य", "suːɾjə"],
    dty: ["घाम", "ɡʱaːm"],
    kfx: ["सूरज", "suːɾədʒ"],
    mr: ["सूर्य", "suːɾjə"],
    lmn: ["सुरज", "suɾədʒ"],
    gu: ["સૂર્ય", "suːɾjə"],
    si: ["ඉර", "ɪɾə"],
    dv: ["އިރު", "iru"],
    te: ["సూర్యుడు", "suːɾjuɖu"],
    kn: ["ಸೂರ್ಯ", "suːɾjə"],
    ml: ["സൂര്യൻ", "suːɾjən"],
    tg: ["офтоб", "oftɒb"],
    ku: ["roj", "ɾoːʒ"],
    ckb: ["خۆر", "xoːɾ"],
    sdh: ["روژ", "ɾoʒ"],
    ps: ["لمر", "lmər"],
    az: ["günəş", "ɟyneʃ"],
    azb: ["گۆنش", "ɡyneʃ"],
    gag: ["güneş", "ɟyˈneʃ"],
    ug: ["قۇياش", "qujɑʃ"],
    kk: ["күн", "kyn"],
    ky: ["күн", "kyn"],
    uz: ["quyosh", "qujɒʃ"],
    tk: ["gün", "ɡyn"],
    mn_cn: ["ᠨᠠᠷᠠ", "nɑrɑ"],
    mnc: ["ᡧᡠᠨ", "ʃun"],
    sjo: ["ᠰᡠᠨ", "sun"],
    ar_eg: ["شمس", "ʃams"],
    ar_lev: ["شمس", "ʃams"],
    ar_gulf: ["شمس", "ʃams"],
    ar_iq: ["شمس", "ʃamis"],
    ar_ma: ["شمس", "ʃəms"],
    arq: ["الشمس", "ʃʃəms"],
    mey: ["الشمس", "əʃʃəms"],
    ar_tn: ["شمس", "ʃams"],
    ar_sd: ["شمس", "ʃams"],
    ti: ["ጸሓይ", "sˤəħaj"],
    mt: ["xemx", "ʃɛmʃ"],
    ig: ["anyanwụ", "aɲaŋwʊ"],
    bom: ["kọs", "kɔs"],
    tiv: ["iyange", "ijaŋɡe"],
    efi: ["utin", "utin"],
    ekp: ["anwu", "aŋwu"],
    izi: ["anwu", "aŋwu"],
    ibb: ["utin", "utin"],
    urh: ["ọvẹ", "ɔvɛ"],
    dge: ["ọvịnị", "ɔvini"],
    ets: ["ovan", "ovan"],
    iso: ["ọvẹ", "ɔvɛ"],
    ha: ["rana", "ɾana"],
    xed: ["vah", "vah"],
    ker: ["kêr", "keːɾ"],
    dbq: ["ɓa", "ɓa"],
    wo: ["jant", "dʒant"],
    srr: ["naangu", "naːŋɡu"],
    so: ["qorrax", "qɔɾːax"],
    om: ["aduu", "aduː"],
    kxc: ["kawa", "kawa"],
    drs: ["ayyaʼne", "ajːaʔne"],
    dsh: ["sicho", "sitʃo"],
    rw: ["izuba", "izuba"],
    rn: ["izuba", "izuba"],
    xh: ["ilanga", "ilaːŋɡa"],
    sn: ["zuva", "zuva"],
    mxc: ["zuva", "zuva"],
    ln: ["mói", "moi"],
    ny: ["dzuwa", "dzuwa"],
    yao: ["lyuwa", "ʎuwa"],
    en_aave: ["sun", "sʌn"],
    en_nz: ["sun", "sɐn"],
    en_au: ["sun", "sɐn"],
    sco: ["sun", "sʌn"],
    af: ["son", "sɔn"],
    de_gsw: ["Sunne", "zunə"],
    de_at: ["Sonne", "sɔnə"],
    de_by: ["Sunn", "zʊn"],
    gsw: ["Sunne", "sʊnə"],
    swg: ["Sonne", "sonə"],
    bar: ["Sun", "sʊn"],
    vmf: ["Sunn", "sʊn"],
    wae: ["Sunna", "sʊnːa"],
    nds: ["Sünn", "zʏn"],
    ksh: ["Sonn", "zɔn"],
    pdc: ["Sunn", "sʊn"],
    pdt: ["Sonn", "zɔn"],
    yi: ["זון", "zun"],
    is: ["sól", "souːl"],
    gd: ["grian", "kɾʲiən"],
    br: ["heol", "heːɔl"],
    nap: ["sole", "solə"],
    scn: ["suli", "suli"],
    vec: ["sol", "sol"],
    co: ["sole", "sɔle"],
    lij: ["sô", "suː"],
    rgn: ["sòl", "ˈsɔl"],
    egl: ["sôl", "ˈsoːl"],
    frp: ["solely", "sɔlɛj"],
    ca: ["sol", "sɔl"],
    gl: ["sol", "sɔl"],
    oc: ["solelh", "suˈlɛʎ"],
    be: ["сонца", "sontsa"],
    cs: ["slunce", "slunt͡sɛ"],
    sk: ["slnko", "slnko"],
    sl: ["sonce", "soːnt͡sɛ"],
    sr: ["сунце", "sunt͡se"],
    bg: ["слънце", "slɤnt͡sɛ"],
    lt: ["saulė", "sɐʊlʲeː"],
    sgs: ["saulė", "sauleː"],
    lv: ["saule", "saulɛ"],
    prg: ["saule", "saule"],
    sq: ["diell", "diɛɫ"],
    aae: ["diell", "diɛɫ"],
    et: ["päike", "pæike"],
    ht: ["solèy", "sɔlɛj"],
    jam: ["son", "sɔn"],
    bah: ["son", "sɔn"],
    bzj: ["son", "sɔn"],
    pap: ["solo", "solo"],
    kea: ["sol", "sɔl"],
    rom: ["kham", "kʰam"],
    rmy: ["kham", "kʰam"],
    rmf: ["kham", "kʰam"],
    pcm: ["sọn", "sɔn"],
    tpi: ["san", "san"],
    ho: ["dina", "dina"],
    kmh: ["nb", "nəb"],
    kmu: ["suka", "suka"],
    emi: ["ariu", "aɾiu"],
    hot: ["ari", "aɾi"],
    fai: ["kibel", "kibel"],
    nlc: ["nyem", "ɲem"],
    bzh: ["gum", "ɡum"],
    tcs: ["san", "san"],
    pis: ["san", "san"],
    hwc: ["san", "sæn"],
    se: ["beaivi", "peɑjvi"],
    sma: ["biejjie", "pie̯jːie"],
    smj: ["biejvve", "pie̯jvːe"],
    smn: ["peivi", "peivi"],
    sms: ["peeiʹvv", "peːjvː"],
    sjd: ["пе̄ййв", "peːjjv"],
    vro: ["päiv", "pæiv"],
    gn: ["kuarahy", "kwaɾahɨ"],
    yrl: ["kuarasi", "kwaɾasi"],
    chr: ["ᏅᏓ", "nʌda"],
    cay: ["gaehkwa", "ɡaehkwa"],
    onn: ["gaeh'kwa", "ɡaehʔkwa"],
    tus: ["hęhts", "hɛ̃hts"],
    as: ["সূৰ্য", "xuɹjɔ"],
    or: ["ସୂର୍ଯ୍ୟ", "suːɾdʒɔ"],
    bho: ["सूरज", "suːɾədʒ"],
    en_south: ["sun", "sʌn"],
    en_app: ["sun", "sʌn"],
    en_in: ["sun", "sʌn"],
    en_ie: ["sun", "sʊn"],
    en_sco: ["sun", "sʌn"],
    en_yk: ["sun", "sʊn"],
    en_ck: ["sun", "sɐn"],
    en_sg: ["sun", "san"],
    fy: ["sinne", "sɪnə"],
    frr: ["saanj", "saːɲ"],
    li: ["zón", "zɔn"],
    nn: ["sol", "suːl"],
    fo: ["sól", "souːl"],
    fr_qc: ["soleil", "sɔlɛj"],
    fr_af: ["soleil", "sɔlɛj"],
    fr_be: ["soleil", "sɔlɛj"],
    fr_ch: ["soleil", "sɔlɛj"],
    es_co: ["sol", "sol"],
    es_cl: ["sol", "sol"],
    es_ar: ["sol", "sol"],
    es_cu: ["sol", "sol"],
    es_pe: ["sol", "sol"],
    es_an: ["sol", "sɔl"],
    lad: ["sol", "sol"],
    rm: ["sulegl", "suleʎ"],
    sc: ["sole", "sole"],
    iu: ["ᓯᕿᓂᖅ", "siqiniq"],
    la: ["sōl", "soːl"],
    el_grc: ["ἥλιος", "hɛ̌ːlios"],
    el_kath: ["ἥλιος", "ˈiʎos"],
    egy: ["𓇳", "riːʕa"],
    en_ang: ["sunne", "sunːe"],
    enm: ["sonne", "sɔnːə"],
    en_em: ["sunne", "sʊn"],
    ang: ["sunne", "sunːe"],
    ofs: ["sunne", "sunːe"],
    non: ["sól", "soːl"],
    got: ["𐍃𐌿𐌽𐌽𐍉", "sunːoː"],
    cu: ["слъньце", "slɤnʲtse"],
    pi: ["सुरिय", "surija"],
    pi_edu: ["suriya", "suɾija"],
    pmh: ["सूर", "suːɾa"],
    cop: ["ⲣⲏ", "reː"],
    arc: ["ܫܡܫܐ", "ʃemʃaː"],
    amw: ["ܫܡܫܐ", "ʃemʃaː"],
    aii: ["ܫܡܫܐ", "ʃimʃa"],
    tsm: ["ܫܡܫܐ", "ʃamʃo"],
    sux: ["𒌓", "utu"],
    akk: ["𒀭𒌓", "ʃamʃu"],
    hit: ["—", "—"],
    nci: ["tōnatiuh", "toːnatiw"],
    nhx: ["tonal", "tonal"],
    nch: ["tonati", "tonati"],
    nhw: ["tonati", "tonati"],
    nhe: ["tonatih", "tonatih"],
    hch: ["tau", "tau"],
    ngu: ["tonatih", "tonatih"],
    ppl: ["tunal", "tunal"],
    crn: ["tahaapuá", "tahaːpwa"],
    myn: ["kʼin", "kʼin"],
    ine: ["*sóh₂wl̥", "sóh₂wl̩"],
    zh_song: ["日", "ʐi˥˩"],
    zh_wenyan_edu: ["日", "jɐt˨"],
    zh_han: ["日", "ȵit"],
    zh_tang: ["日", "ȵit"],
    ja_edo: ["日", "hi"],
    ja_kanbun: ["日", "hi"],
    ja_heian: ["日", "ɸi"],
    ja_chu: ["日", "ɸi"],
    pry: ["*teda", "teda"],
    ko_mid: ["ᄒᆡ", "hʌj"],
    oko: ["日", "*hai"],
    okg: ["—", "—"],
    ko_gor: ["姮", "*hai"],
    ko_em: ["ᄒᆡ", "hɛ"],
    vi_han: ["日", "ɲət˨˩"],
    vi_nom: ["𩈘𡗶", "mət tɤj"],
    eo: ["suno", "suno"],
    vo: ["sol", "sol"],
    ina: ["sol", "sol"],
    ia: ["sol", "sɔl"],
    tok: ["suno", "suno"],
    tlh: ["jul", "dʒul"],
    jbo: ["solri", "solri"],
    cjy: ["日头", "ʐəʔ˨tʰəu˩"],
    hsn: ["太阳", "tʰai˥˩ian˩˧"],
    gan: ["日头", "ɲit˥tʰɛu"],
    mai: ["सूरज", "suːrəd͡ʒ"],
    anp: ["सूरज", "suːrədʒ"],
    awa: ["सूरज", "suːrəd͡ʒ"],
    thr: ["सूरज", "suːrədʒ"],
    bra: ["सूरज", "suːrəd͡ʒ"],
    skr: ["سُورج", "suːrəd͡ʒ"],
    sat: ["ᱥᱤᱸᱜᱤ", "siŋɡi"],
    kru: ["बेरी", "beɾiː"],
    mad: ["are", "are"],
    hil: ["adlaw", "adlaw"],
    cbk: ["sol", "sol"],
    bal: ["روچ", "roːtʃ"],
    ak: ["owia", "oɥia"],
    ada: ["hyɛ", "çɛ"],
    gaa: ["hulu", "hulu"],
    nzi: ["ewia", "ewia"],
    mk: ["сонце", "ˈsɔnt͡sɛ"],
    lg: ["enjuba", "eɲɟuba"],
    zne: ["urure", "uɾuɾe"],
    myx: ["suuba", "suːba"],
    bxk: ["liuba", "liuba"],
    ki: ["rĩũa", "ɾiwa"],
    mer: ["rĩũa", "ɾiua"],
    kam: ["syũa", "sjua"],
    ebu: ["rĩũa", "ɾiua"],
    tn: ["letsatsi", "letsatsi"],
    st: ["letsatsi", "letsatsi"],
    ts: ["dyambu", "dʒambu"],
    ve: ["ḓuvha", "ɖuʋa"],
    bem: ["akasuba", "akasuba"],
    kqn: ["juba", "dʒuba"],
    lua: ["dîba", "diːba"],
    kg: ["ntangu", "ntaŋɡu"],
    lol: ["lokɔlɔ", "lokɔlɔ"],
    tll: ["ondelo", "ondelo"],
    ff: ["naange", "naːŋɡe"],
    bm: ["tile", "tile"],
    ddn: ["naa", "naː"],
    emk: ["tile", "tile"],
    kao: ["tile", "tile"],
    snk: ["kiye", "kije"],
    mwk: ["tle", "tle"],
    mlq: ["tile", "tile"],
    mev: ["lɛ", "lɛ"],
    dnj: ["lai", "lai"],
    ses: ["wayna", "wajna"],
    khq: ["wari", "wari"],
    dje: ["wayna", "wajna"],
    kab: ["iṭij", "itˤiʒ"],
    yua: ["kʼiin", "kʼiːn"],
    ncs: ["—", "—"],
    itz: ["k'in", "kʼin"],
    usp: ["q'iij", "qʼiːh"],
    tzo: ["kʼakʼal", "kʼakʼal"],
    tzh: ["kʼajkʼal", "kʼaxkʼal"],
    mix: ["nikandii", "nikandiː"],
    zap: ["gubidxa", "ɡubidʒa"],
    zts: ["gubi", "ɡubi"],
    maz: ["hyadi", "hjadi"],
    xtm: ["nikan", "nikan"],
    mxv: ["nikandii", "nikandiː"],
    toc: ["chichiní", "tʃitʃiní"],
    huv: ["nüt", "nɨt"],
    ay: ["inti", "inti"],
    jaq: ["ñiwi", "ɲiwi"],
    cni: ["oorya", "oːɾja"],
    ame: ["mtsho", "mt͡so"],
    gym: ["ngwen", "ŋʷen"],
    sum: ["waiku", "waiku"],
    jiv: ["etsa", "etsa"],
    agr: ["etsá", "etsá"],
    acu: ["etsa", "etsa"],
    car: ["weju", "weju"],
    pbb: ["sek", "seɡ"],
    gum: ["shi", "ʃi"],
    arn: ["antü", "antɨ"],
    cr: ["ᐱᓯᒼ", "piːsim"],
    chp: ["sa", "sa"],
    oj: ["giizis", "ɡiːzis"],
    atj: ["pisim", "pisim"],
    mic: ["naku'set", "naɡuʔset"],
    pqm: ["kisuhs", "kisuhs"],
    abe: ["kisos", "kisos"],
    umu: ["kíishux", "kiːʃux"],
    crk: ["ᐱᓰᒼ", "piːsim"],
    yur: ["woygey", "wojɡej"],
    lkt: ["wí", "wí"],
    kl: ["seqineq", "seqineq"],
    ce: ["малх", "malx"],
    inh: ["малх", "malx"],
    av: ["бакъ", "baq"],
    lez: ["рагъ", "raʁ"],
    dar: ["берхӏи", "beɾħi"],
    agx: ["рагъ", "raʁ"],
    ddo: ["буцӏ", "butsʼ"],
    lbe: ["бургъ", "burʁ"],
    tab: ["рагъ", "raʁ"],
    aqc: ["бараг", "baɾaɡ"],
    udi: ["бех", "beχ"],
    tkr: ["верг", "verɡ"],
    kum: ["гюн", "ɡʲun"],
    nog: ["кьяс", "qjas"],
    ady: ["тыгъэ", "təʁa"],
    kbd: ["дыгъэ", "dəʁa"],
    ab: ["амра", "amra"],
    abq: ["амра", "amra"],
    uby: ["dəɣʷa", "dəɣʷa"],
    xmf: ["ბჟა", "bʒa"],
    os: ["хур", "xur"],
    ty: ["mahana", "mahana"],
    niu: ["lā", "laː"],
    tvl: ["laa", "laː"],
    rap: ["ra'ā", "raʔaː"],
    rar: ["rā", "raː"],
    mh: ["aḷ", "alˠ"],
    gil: ["tai", "tai"],
    ch: ["atdao", "atdao"],
    tet: ["loron", "loɾon"],
    tdt: ["loron", "loɾon"],
    aoz: ["manas", "manas"],
    bi: ["san", "san"],
    pip: ["san", "san"],
    pjt: ["tjintu", "cintu"],
    wbp: ["wantajarra", "wantadʒaɻa"],
    piu: ["tjintu", "cintu"],
    aer: ["arrenge", "aɾɛŋe"],
    nha: ["ngama", "ŋama"],
    olg: ["naŋkari", "naŋkaɻi"],
    adt: ["yidnu", "jidnu"],
    nys: ["ngangk", "ŋaŋk"],
    xul: ["guma", "ɡuma"],
    wbt: ["tjirntu", "cinʈu"],
    mni: ["ꯅꯨꯃꯤꯠ", "numit"],
    bpy: ["বিল", "bil"],
    new: ["सूर्य", "surja"],
    lif: ["ᤛᤡᤥᤔᤡ", "ɲaːmpʰʌ"],
    tdh: ["नाम", "nam"],
    brx: ["सान", "san"],
    adi: ["donyi", "doɲi"],
    nag: ["suruj", "suɾudʒ"],
    nzm: ["sʰeu", "ʃeu"],
    nmf: ["nyithui", "ɲitʰui"],
    lus: ["ni", "ni"],
    dz: ["ཉི་མ", "ɲima"],
    xsr: ["ཉི་མ", "ɲima"],
    xkz: ["ningpe", "niŋpe"],
    sik: ["ཉི་མ", "ɲima"],
    min: ["matoari", "matoaɾi"],
    nia: ["luo", "luo"],
    ban: ["matanai", "matanai"],
    ace: ["mata uroe", "mata uɾoe"],
    gay: ["matacana", "matatʃana"],
    bug: ["mata esso", "mata esːo"],
    mdr: ["mata allo", "mata alːo"],
    war: ["adlaw", "adlaw"],
    bik: ["aldaw", "aldaw"],
    bto: ["aldəw", "aldəw"],
    tum: ["zuva", "zuva"],
    kde: ["lyuva", "ʎuβa"],
    seh: ["dzuwa", "dzuwa"],
    ngl: ["nsuwa", "nsuwa"],
    din: ["akɔ̈l", "akɔl"],
    nus: ["caŋ", "tʃaŋ"],
    anu: ["ceeŋ", "tʃeːŋ"],
    luo: ["chieng'", "tʃieŋ"],
    mas: ["enkolong", "eŋkoloŋ"],
    aue: ["xìbé", "χíbé"],
    bfa: ["kolong", "koloŋ"],
    saq: ["lakwa", "lakʷa"],
    aa: ["ayró", "ajɾɔ"],
    shi: ["tafukt", "tafukt"],
    rif: ["dhish", "ðiʃ"],
    shy: ["ittij", "itʃiʒ"],
    mwr: ["सूरज", "suːɾədʒ"],
    bgc: ["सूरज", "suːɾədʒ"],
    ks: ["آفتاب", "aːftaːb"],
    kok: ["सूर्य", "suɾjə"],
    mnp: ["日头", "ni˥˥tʰau˨˨"],
    nan_te: ["日头", "ʒik˥˥tʰau˥˥"],
    yue_ts: ["日头", "ɲit˨˨hau˧˧"],
    czh: ["日头", "ʐɨ˨˦tʰəu"],
    cnp: ["日头", "ŋit˨tʰɐu˦˦"],
    zh_jh: ["日头", "ʐəʔ˦˦tʰəu˨˦"],
    zh_tj: ["日头", "ʐʅ˥˩tʰoʊ˨˦"],
    zh_lz: ["日头", "ʐɨ˨˦tʰəu˨˦"],
    dng: ["жѳтў", "ʐətʰu"],
    hsb: ["słónco", "ˈswʊnt͡sɔ"],
    csb: ["słuńce", "ˈswuɲt͡sɛ"],
    rue: ["сонце", "ˈsont͡se"],
    fur: ["soreli", "soˈreːli"],
    ast: ["sol", "sol"],
    ext: ["sol", "sɔl"],
    fla: ["sol", "sɔl"],
    an: ["sol", "sol"],
    rup: ["soare", "ˈsoare"],
    ruq: ["soari", "ˈsoari"],
    wa: ["solea", "soˈlea"],
    kpv: ["шонді", "ʃondi"],
    koi: ["шонді", "ʃondi"],
    udm: ["шунды", "ʃundɨ"],
    mhr: ["кече", "ketʃe"],
    mrj: ["кечӹ", "ketʃʉ"],
    myv: ["чи", "tʃi"],
    mdf: ["ши", "ʃi"],
    krl: ["päivy", "ˈpæjvy"],
    olo: ["päivy", "ˈpæjvy"],
    vep: ["päiväine", "ˈpæivæine"],
    vot: ["päivä", "ˈpæivæ"],
    liv: ["pǟva", "pæːva"],
    mzn: ["آفتاب", "ɒːftɒːb"],
    glk: ["آفتاب", "ɒːftɒːb"],
    lrc: ["هور", "hovaɾ"],
    crh: ["küneş", "kyneʃ"],
    tt: ["кояш", "qojaʃ"],
    ba: ["ҡояш", "qojaʃ"],
    krc: ["кюн", "kyn"],
    ksw: ["မုၢ်", "mu"],
    pwo: ["မုၢ်", "mə"],
    lhu: ["mvuhˇ-nyiˉ", "mvuʔ ɲí"],
    lis: ["mei-lo", "mejlo"],
    nxq: ["ny-mei", "nĩ˧mi˧"],
    shn: ["ဝၼ်း", "wan"],
    jia: ["mau", "mau"],
    kbp: ["wɩsɩ", "wɩsɩ"],
    ee: ["ɣe", "ɣe"],
    gej: ["ɣe", "ɣe"],
    aja: ["eŋke", "eŋke"],
    nyn: ["izooba", "izoːba"],
    cgg: ["eizooba", "eizoːba"],
    ttj: ["eizooba", "eizoːba"],
    nyo: ["eizooba", "eizoːba"],
    luy: ["liuba", "liuba"],
    ssw: ["lilanga", "lilaŋɡa"],
    nbl: ["ilanga", "ilaŋɡa"],
    nd: ["ilanga", "ilaŋɡa"],
    nso: ["letšatši", "letʃatʃi"],
    fan: ["zòp", "zop"],
    naq: ["sores", "soɾes"],
    hts: ["ʼisha", "ʔiʃa"],
    nmn: ["ǁʼân", "ǁʼã"],
    kr: ["kiŋal", "kiŋal"],
    men: ["foni", "foni"],
    vai: ["ꕒꔧ", "foɛ"],
    tem: ["arɛ", "arɛ"],
    dyu: ["tile", "tile"],
    bbo: ["tile", "tile"],
    spp: ["kanha", "kaɲa"],
    sus: ["soge", "soɡe"],
    syl: ["সুরুজ", "suruz"],
    rhg: ["beil", "beil"],
    ctg: ["সূর্য", "surdʒo"],
    mag: ["सूरज", "suːraj"],
    doi: ["सूरज", "suːraj"],
    xkk: ["maŋ", "maŋ"],
    moh: ["karahkwa", "karahkwa"],
    cho: ["hashi", "haʃi"],
    mus: ["hvse", "hasi"],
    esu: ["akerta", "akerta"],
    ipk: ["siqiñiq", "siqiɲiq"],
    ess: ["маасьихта", "maːsʲixta"],
    ale: ["агадгих̆", "aɡaðɣiχ"],
    apw: ["shánda'á", "ʃandaʔa"],
    dak: ["aŋpétuwí", "aŋpétuwí"],
    chy: ["éše'he", "eˀʃeˀhe"],
    arp: ["hiʼíísh", "hiʔíːʃ"],
    kio: ["phî", "pʰîː"],
    lmo: ["sô", "soː"],
    pms: ["sol", "sol"],
    eml: ["sòul", "sɔul"],
    mwl: ["sol", "sɔl"],
    pnt: ["ήλεν", "ˈilen"],
    hno: ["سورج", "soːraj"],
    bhb: ["सूरज", "suːraj"],
    cja: ["aditiak", "aditiak"],
    hmo: ["dina", "dina"],
    meu: ["dina", "dina"],
    pon: ["ketipin", "ketipin"],
    kos: ["fihl", "fihl"],
    myz: ["ࡔࡀࡌࡔࡀ", "ʃamʃa"],
    vmw: ["ettsuwa", "etsuwa"],
    dsb: ["słyńco", "ˈswɨnt͡sɔ"],
    gv: ["grian", "ɡrʲan"],
    kw: ["howl", "haʊl"],
    zza: ["tîj", "tiːʒ"],
    brh: ["دے", "deː"],
    mrq: ["ʻoumati", "ʔoumati"],
    tiw: ["pumarli", "pumarli"],
    lbz: ["thurara", "θuɾaɾa"],
    lbz_damin: ["—", "—"],
    nny: ["wargu", "waɾɡu"],
    kky: ["ngalan", "ŋalan"],
    guc: ["kaʼi", "kaʔi"],
    mch: ["shi", "ʃi"],
    wba: ["ya", "ja"],
    mzh: ["ifwala", "ifʷala"],
    myp: ["hisi", "hisi"],
    tue: ["—", "—"],
    emp: ["hewa", "hewa"],
    kpe: ["pelei", "pelei"],
    bsq: ["plɔ", "plɔ"],
    loz: ["lizazi", "lizazi"],
    bbc: ["mata ni ari", "mata ni ari"],
    bts: ["mata ni ari", "mata ni ari"],
    akb: ["ari", "ari"],
    bjn: ["matahari", "matahari"],
    abs: ["mata hari", "mata hari"],
    max: ["matahari", "matahari"],
    mui: ["matahari", "matahari"],
    sas: ["mataari", "mataari"],
    kha: ["ka sngi", "ka sŋi"],
    mns: ["хотал", "xotal"],
    mrw: ["alongan", "aloŋan"],
    tsg: ["suga", "suɡa"],
    yap: ["yaal", "jaːl"],
    chk: ["akkar", "akːaɾ"],
    gbm: ["सूरज", "suːraj"],
    kfy: ["स्यू", "sjuː"],
    xnr: ["सूरज", "suːraj"],
    hr: ["sunce", "ˈsuːnt͡se"],
    bs: ["sunce", "ˈsunt͡se"],
    iba: ["mata-ari", "mataari"],
    ljp: ["matarani", "matarani"],
    tzm: ["tafukt", "tafukt"],
    tmh: ["tafuk", "tafuk"],
    ng: ["etango", "etaŋɡo"],
    kj: ["etango", "etaŋɡo"],
    umb: ["ekumbi", "ekumbi"],
    kmb: ["muanya", "mwaɲa"],
    lue: ["likumbi", "likumbi"],
    her: ["eyuva", "ejuva"],
    xal: ["нарн", "narn"],
    sg: ["lâ", "la"],
    toi: ["zuba", "zuba"],
    peo: ["𐏃𐎢𐎺𐎼", "huwar"],
    ave: ["𐬵𐬎𐬎𐬀𐬭𐬆", "huwarə"],
    xto: ["𑀓𑁄𑀦𑁆𑀢𑀼", "kontu"],
    txb: ["𑀓𑁅𑀁", "kauŋ"],
    phn: ["𐤔𐤌𐤔", "ʃameʃ"],
    uga: ["𐎌𐎔𐎌", "ʃapʃ"],
    xlu: ["𔖻𔗬𔑯", "tiwad"],
    pal: ["𐭧𐭥𐭫𐭱𐭩𐭲", "xwarʃeːd"],
    fa_clas: ["خورشید", "xʷarʃeːd"],
    syc: ["ܫܡܫܐ", "ʃemʃaː"],
    fro: ["soleil", "soˈleʎ"],
    fr_class: ["soleil", "sɔlɛj"],
    it_dan: ["sole", "ˈsole"],
    goh: ["sunna", "ˈsunna"],
    gez: ["ፀሐይ", "sˤaħaj"],
    gmy: ["𐀀𐀺𐀂𐀍", "haːwelios"],
    xct_litpr: ["ཉི་མ", "ɲima"],
    xct: ["ཉི་མ", "ɲima"],
    xpu: ["𐤔𐤌𐤔", "ʃameʃ"],
    xhu: ["𒅆𒈨𒄀", "ʃimeɡi"],
    elx: ["𒀭𒈾𒄴𒄭𒌅", "nahhunte"],
    xsa: ["𐩦𐩣𐩪", "ʃams"],
    kaw: ["ꦱꦸꦂꦪ", "suɾja"],
    kho: ["𑀉𑀭𑁆𑀫", "urma"],
    de_lut: ["Sonne", "ˈzɔnə"],
    gmh: ["sunne", "ˈzunːə"],
    es_sgl: ["sol", "sol"],
    osp: ["sol", "sol"],
    okz: ["ព្រះអាទិត្យ", "preh ʔaːtit"],
    osx: ["sunna", "ˈsunːa"],
    smg: ["izuba", "izuba"],
    mos: ["wəntinga", "wəntinɡa"],
    maw: ["wuntiri", "wuntiri"],
    kln: ["asis", "asis"],
    mfe: ["soley", "soleɪ"],
    rcf: ["soley", "solej"],
    crs: ["soley", "solej"],
    gcf: ["solèy", "solɛj"],
    mnk: ["tilo", "tilo"],
    bqi: ["خور", "xor"],
    unr: ["singi", "siŋɡi"],
    hoc: ["singi", "siŋɡi"],
    enq: ["niko", "niko"],
    xpr: ["xwar", "xwar"],
    xqa: ["kün", "kyn"],
    sga: ["grían", "ɡrian"],
    bsk: ["sá", "saː"],
    yag: ["мет", "met"],
    srn: ["son", "soŋ"],
    djk: ["son", "soŋ"],
    srm: ["masángi", "masáŋɡi"],
    kwk: ["ƛ'isa̱la", "tɬʼisəla"],
    blc: ["snx", "snx"],
    sad: ["kʼɔɔ", "kʼɔː"],
    pcc: ["ngonzbyaaiz", "ŋon˩˩pjaːi˩˩"],
    iuu: ["hnoi", "hnoi˧"],
    hui: ["nogo", "noɡo"],
    tkl: ["la", "la"],
    squ: ["snexwílh", "snexʷiɬ"],
    mga: ["grían", "ɡrian"],
    hbo: ["שמש", "ʃemeʃ"],
    he_mis: ["חמה", "ħamːa"],
    hy_grab: ["արեւ", "ɑɾɛw"],
    mpt: ["kep", "kep"],
    ygr: ["kena", "kena"],
    roo: ["ravireo", "raβiɾeo"],
    quz: ["inti", "inti"],
    quy: ["inti", "inti"],
    shp: ["bari", "bari"],
    cab: ["weyu", "weju"],
    crx: ["sa", "sa"],
    tsi: ["gyemk", "ɡjemk"],
    thp: ["skwekwsim", "skʷekʷsim"],
    wbl: ["йир", "jir"],
    psi: ["سور", "sur"],
    bgq: ["सूरज", "suːraj"],
    laj: ["ceŋ", "tʃeŋ"],
    ach: ["ceng", "tʃeŋ"],
    rki: ["နေ", "neː"],
    cnh: ["ni", "ni"],
    kxm: ["ថ្ងៃ", "tŋai"],
    xng: ["ᠨᠠᠷᠠᠨ", "naran"],
    ja_kg: ["お日さん", "ohisaɴ"],
    ja_sd: ["お日さま", "ohisama"],
    ko_hg: ["해", "hɛ"],
    ko_jl: ["해", "hɛ"],
    nan_pn: ["日頭", "lit˥˥tʰau˨˨"],
    mra: ["ŋay", "ŋai"],
    wuu_nb: ["日头", "ɲiʔ˩˨dɤu"],
    yue_gz: ["日头", "jɐt˥˥tʰɐu˧˧"],
    khb: ["ᦋᧁᧉ", "tsau"],
    blt: ["ꪼꪎ", "sai˨˦"],
    pam: ["aldo", "ʔalˈdoʔ"],
    pag: ["agew", "ˈʔaɡew"],
    mdh: ["senang", "seˈnaŋ"],
    gor: ["mata lo dulahu", "mata lo duˈlahu"],
    mak: ["mata allo", "mata ˈʔallo"],
    fon: ["hwe", "xʷe"],
    kri: ["san", "san"],
    dag: ["wuntaŋa", "wuntaŋa"],
    xog: ["enjuba", "eɲɟuba"],
    teo: ["akolong", "akoloŋ"],
    dyo: ["funak", "funak"],
    bci: ["wia", "wia"],
    tcy: ["ಸೂರ್ಯ", "suːrja"],
    haz: ["آفتو", "ɑːftow"],
    tly: ["rüj", "ɾyʒ"],
    kaa: ["kún", "kyn"],
    bej: ["yint", "jint"],
    tig: ["ጸሓይ", "tsʼəħaj"],
    byn: ["ኤርሕ", "erəħ"],
    ssy: ["ayro", "ajɾo"],
    ewo: ["dzōb", "dʒoːb"],
    bum: ["zobé", "zobe"],
    agq: ["kû'", "kuʔ"],
    mgo: ["nyam", "ɲam"],
    dur: ["ngə̄ə̀", "ŋɡəə"],
    ndc: ["zuva", "zuva"],
    ote: ["hyadi", "hjadi"],
    otq: ["hyadi", "hjadi"],
    tar: ["rayó", "ɾajo"],
    orv: ["сълньце", "sŭlnĭtse"],
    xsc: ["hvar", "xʷar"],
    sukh: ["ตะวัน", "tawan"],
    xmr: ["𐦨𐦬", "ms"],
    onw: ["ⲙⲁⲥⲁⲗ", "masal"],
    cqu: ["inti", "inti"],
    omc: ["jiang", "dʒiaŋ"],
    chb: ["súa", "sua"],
    oma: ["matari", "matari"],
    osu: ["poé", "poe"],
    otl: ["ᜀᜇᜏ᜔", "araw"],
    zkt: {
      form: "𘲺",
      ipa:  "nair",
      alt: [
        { form: "nair", script: "Latin (Kane 2009 reading)", source: "Kane (2009) Index of Graphs #159 — Khitan *nair (sun / day), cognate Mongolic nara." },
      ],
    },
    juc: {
      form: "šun",
      ipa:  "ʃun",
      alt: [
        { form: "順", script: "Chinese-character transliteration", source: "女真譯語; 順 = šun" },
      ],
    },
    omx: ["တ္ၚဲ", "tŋai"],
    pyx: ["ño", "ɲo"],
    obr: ["နိ", "niy"],
    occ: ["aṇdaw", "ʔadaw"],
    och: ["日", "*C.nik"],
    ojp: ["日", "pi"],
    pjk: ["—", "—"],
    vsa: ["सूर्यः", "suːrjaɦ"],
    txg: ["𘂴", "pjij˧˥"],
    sog: ["xwr", "xwar"],
    otk: ["𐰚𐰰𐰣", "kyn"],
    ami: ["cidal", "tʃidal"],
    pwn: ["qadaw", "qadaw"],
    tay: ["wagi'", "waɡiʔ"],
    bnn: ["vali", "vali"],
    trv: ["hidaw", "hidaw"],
    tsu: ["hie", "hie"],
    tao: ["araw", "araw"],
    pyu: ["kadaw", "kadaw"],
    szy: ["cidal", "tʃidal"],
    ssf: ["fitulha", "fituʎa"],
    hak_tw: ["日頭", "ŋit˨ tʰeu˩˩"],
    wuu_sz: ["太阳", "tʰɛ˧˧ɦiɔ̃˨˧"],
    wuu_wz: ["日头", "zai˨˩˧dau˧˩"],
    nan_qz: ["日頭", "d͡ʑit˨˨tʰau˨˦"],
    nan_hai: ["日头", "dit˨˨tʰau˨˦"],
    zh_wh: ["太阳", "tʰai˥˧ian˨˩˧"],
    zh_zz: ["太阳", "tʰai˨˩iaŋ˨˩˧"],
    hak_hl: ["日頭", "ŋit˨˨tʰeu˨˦"],
    cpx: ["日头", "lit˥˥tʰau˧˧"],
    mfa: ["matari", "mataʁe"],
    mtq: ["mặt côi", "məːt koːi"],
    tyz: ["tha vằn", "tʰaː˧˧vən˨˩"],
    kjp: ["မုန်", "mu˧"],
    kac: ["jan", "tsan˧"],
    wbm: ["cangaiʔ", "tʃaŋaiʔ"],
    pll: ["saŋi", "saŋi"],
    ahk: ["nyi ma", "ɲi˧ma˧"],
    dtp: ["todau", "todau"],
    hne: ["सूरज", "suːrəj"],
    mnw: ["တ္ၚဲ", "tŋoa"],
    bru: ["mat plei", "mat plei"],
    bdq: ["mat trơ", "mat trə"],
    lwl: ["vüa", "vɨa"],
    grt: ["sal", "sal"],
    nut: ["tha vằn", "tʰaː˧˧vən˨˩"],
    quc: ["qʼij", "qʼih"],
    cak: ["qʼij", "qʼih"],
    kek: ["saqʼe", "saqʼe"],
    poh: ["qʼij", "qʼih"],
    kjb: ["kʼuʼ", "kʼuʔ"],
    ctu: ["kʼajn", "kʼahn"],
    toj: ["k'ak'u", "kʼakʼu"],
    bzd: ["siwa", "siwa"],
    cuk: ["olo", "olo"],
    chf: ["kʼin", "kʼin"],
    agu: ["qʼijl", "qʼihl"],
    ixl: ["qʼii", "qʼiː"],
    mam: ["qʼij", "qʼiχ"],
    mvc: ["q'iij", "qʼiːh"],
    wal: ["awa", "awa"],
    sid: ["arrishshe", "arːiʃːe"],
    tji: ["ni", "ni˧˥"],
    nij: ["matanandau", "matananˈdau"],
    sda: ["mata allo", "mataʔalːo"],
    lld: ["surëdl", "suˈrəːdl"],
    stq: ["Sunne", "ˈzʊnə"],
    wym: ["zóner", "ˈtsɔnɐ"],
    yuc: ["dethla", "dɛθla"],
    kgg: ["nəm", "nəm"],
    ota: ["كونش", "ɡyˈneʃ"],
    cmg: ["ᠨᠠᠷᠠᠨ", "naran"],
    ett: ["usil", "ˈuzil"],
    cms: ["—", "—"],
    xht: ["eštan", "ɛʃtan"],
    txr: ["—", "—"],
  },
};
