/**
 * thanks — see docs/words/CONTRIBUTING.md for editing guidance.
 * Language codes: see docs/words/LANG_CODES.md.
 */
WORDS.thanks = {
  label: {
    en: "Thank you",
    ja: "ありがとう",
    ko: "감사",
    zh: "谢谢",
    yue: "多謝",
    vi: "Cảm ơn",
    th: "ขอบคุณ",
    id: "Terima kasih",
    hi: "धन्यवाद",
    de: "Danke",
    fr: "Merci",
    it: "Grazie",
    es: "Gracias",
    es_eu: "Gracias",
    es_mx: "Gracias",
    pt: "Obrigado",
    pt_eu: "Obrigado",
    pt_br: "Obrigado",
    ru: "Спасибо",
    uk: "Дякую",
    ar: "شكرا",
    he: "תודה",
    sw: "Asante",
  },
  definition: {
    en: "Spoken thank-you formula for modern languages. For historical languages, use — or a clearly noted liturgical/gratitude noun rather than inventing a formula.",
    ja: "現代語では話し言葉の感謝表現。歴史言語では「—」または明記された宗教/感謝名詞を用い、表現を捏造しない。",
    ko: "현대어에서는 구어 감사 표현. 역사 언어에서는 \"—\" 또는 명기된 종교/감사 명사를 사용하고 임의로 만들어내지 않음.",
    zh: "现代语言使用口语感谢表达。历史语言用 \"—\" 或明确标注的礼仪/感谢名词，而非杜撰表达。",
    yue: "現代語：口語感謝表達。歷史語言用「—」或者明確標記嘅祈福／感謝名詞，唔好捏造。",
    vi: "Lời cảm ơn nói thường ngày trong ngôn ngữ hiện đại. Ngôn ngữ lịch sử dùng \"—\" hoặc danh từ tạ ơn có chú giải, không bịa.",
    th: "คำขอบคุณเชิงพูดในภาษาสมัยใหม่ ภาษาประวัติศาสตร์ใช้ \"—\" หรือคำนามขอบคุณ/ศาสนา; ห้ามสร้างขึ้นเอง",
    id: "Ungkapan terima kasih sehari-hari untuk bahasa modern. Bahasa historis pakai \"—\" atau kata benda doa/syukur yang dicatat; jangan mengarang.",
    hi: "आधुनिक भाषाओं के लिए मौखिक धन्यवाद। ऐतिहासिक भाषाओं में \"—\" या स्पष्ट रूप से नोट किया गया धार्मिक/कृतज्ञता संज्ञा; कुछ गढ़ें नहीं।",
    de: "Mündliche Dankesformel für moderne Sprachen. Bei historischen Sprachen \"—\" oder ein klar belegtes liturgisches/ Dank-Substantiv — nichts erfinden.",
    fr: "Formule orale de remerciement pour les langues modernes. Pour les langues historiques, utiliser \"—\" ou un nom de gratitude/liturgique attesté — ne pas inventer.",
    it: "Formula orale di ringraziamento nelle lingue moderne. Per quelle storiche, usare \"—\" o un sostantivo di gratitudine/liturgico documentato — niente invenzioni.",
    es: "Fórmula oral de agradecimiento en lenguas modernas. En lenguas históricas, usar \"—\" o un sustantivo de gratitud/litúrgico atestiguado; no inventar.",
    es_eu: "Fórmula oral de agradecimiento en lenguas modernas. En lenguas históricas, usar \"—\" o un sustantivo de gratitud/litúrgico atestiguado; no inventar.",
    es_mx: "Fórmula oral de agradecimiento en lenguas modernas. En lenguas históricas, usar \"—\" o un sustantivo de gratitud/litúrgico atestiguado; no inventar.",
    pt: "Fórmula oral de agradecimento em línguas modernas. Em línguas históricas, usar \"—\" ou um substantivo de gratidão/litúrgico atestado; não inventar.",
    pt_eu: "Fórmula oral de agradecimento em línguas modernas. Em línguas históricas, usar \"—\" ou um substantivo de gratidão/litúrgico atestado; não inventar.",
    pt_br: "Fórmula oral de agradecimento em línguas modernas. Em línguas históricas, usar \"—\" ou um substantivo de gratidão/litúrgico atestado; não inventar.",
    ru: "Устная формула благодарности для современных языков. В исторических — \"—\" или явно отмеченное литургическое/благодарственное существительное; не выдумывать.",
    uk: "Усна формула подяки для сучасних мов. У історичних — \"—\" або явно позначений літургійний/вдячний іменник; не вигадувати.",
    ar: "صيغة شكر شفوية في اللغات الحديثة. في اللغات التاريخية، استخدم \"—\" أو اسمًا ليتورجيًّا/شكرًا موثّقًا؛ لا تختلق.",
    he: "נוסח תודה דיבורי בשפות מודרניות. בשפות היסטוריות — \"—\" או שם עצם תודתי/ליטורגי מתועד; אין להמציא.",
    sw: "Msemo wa kuthamini wa kunena katika lugha za kisasa. Kwa lugha za kihistoria tumia \"—\" au nomino ya shukrani/kiimani iliyotajwa; usitunge.",
  },
  data: {
    ja: ["ありがとう", "aɾiɡatoː"],
    ja_osa: ["おおきに", "oːkini"],
    ja_aom: ["ありがどー", "aɾiɡadoː"],
    ja_oki: ["にふぇーでーびる", "niɸeːdeːbiɾu"],
    ja_hak: ["ありがとう", "aɾiɡatoː"],
    ja_kyo: ["おおきに", "oːkini"],
    ja_hir: ["ありがとう", "aɾiɡatoː"],
    ja_mvi: ["たんでぃがーたんでぃ", "tandiɡaːtandi"],
    ja_rys: ["みーふぁいゆー", "miːɸaijuː"],
    ko: ["고맙습니다", "komapsɯmnida"],
    ko_kp: ["고맙습니다", "komapsɯmnida"],
    ko_bus: ["고맙습니다", "komap̚sɯmnida"],
    ko_jeju: ["고맙수다", "komap̚suda"],
    ko_yb: ["고맙습니다", "komapsɯmnida"],
    zh: ["谢谢", "ɕjɛ˥˩ɕjɛ"],
    yue: ["多謝", "tɔː˥t͡ɕɛː˨"],
    nan: ["多謝", "to˥sia˧"],
    wuu: ["谢谢", "ʑia˩ʑia"],
    hak_cn: ["多谢", "to˥t͡sia˧"],
    vi: ["cảm ơn", "kaːm˧˩˧ əːn˥"],
    vi_c: ["cảm ơn", "kaːm˧˩ əːn˥"],
    vi_s: ["cảm ơn", "kaːm˨˩˥ əːn˥"],
    th: ["ขอบคุณ", "kʰɔːp˨˩kʰun˧"],
    id: ["terima kasih", "tərima kasih"],
    ms: ["terima kasih", "tərima kasih"],
    hi: ["धन्यवाद", "dʰanjaʋaːd"],
    hns: ["dhanyabaad", "dʰanjabaːd"],
    sa_edu: ["धन्यवादाः", "dʰanjaʋaːdaːɦ"],
    sa: ["धन्यवादः", "dʰanjaʋaːdaɦ"],
    bn: ["ধন্যবাদ", "dʰɔnnobad"],
    rkt: ["ধইন্যা", "dʱoinɲa"],
    ur: ["شکریہ", "ʃukrijaː"],
    ta: ["நன்றி", "nanri"],
    iru: ["nanri", "nanɾi"],
    en: ["thank you", "θæŋk juː"],
    de: ["Danke", "daŋkə"],
    fr: ["merci", "mɛʁsi"],
    pcd: ["merci", "mɛʁsi"],
    nrf: ["mèsi", "mɛsi"],
    it: ["grazie", "ˈɡratt͡sje"],
    es_eu: ["gracias", "ˈɡɾaθjas"],
    es_mx: ["gracias", "ɡɾasjas"],
    pt_eu: ["obrigado", "obɾiɡadu"],
    pt_br: ["obrigado", "obɾiɡadu"],
    ru: ["спасибо", "spɐsʲibɐ"],
    ar_qur: ["الحمد لله", "al.ħamdu lillaːh"],
    ar: ["شكرا", "ʃukran"],
    he: ["תודה", "toda"],
    tr: ["teşekkürler", "teʃecːyɾleɾ"],
    fa: ["سپاس", "sepɒːs"],
    jpr: ["ספאס", "sepɒːs"],
    prs: ["تشکر", "taʃakkoɾ"],
    trm: ["shukria", "ʃukɾia"],
    sw: ["asante", "asante"],
    suk: ["nakulumba", "nakulumba"],
    nym: ["twaβakaβa", "twabakaba"],
    rim: ["ahsante", "ahsante"],
    ksb: ["ahsante", "ahsante"],
    jmc: ["ahsànte", "ahsante"],
    sbp: ["nashukulu", "naʃukulu"],
    rwk: ["asante", "asante"],
    asu: ["mwasanga", "mwasaŋɡa"],
    tl: ["salamat", "salamat"],
    agt: ["salamat", "salamat"],
    mn: ["баярлалаа", "bajarɮaɮaː"],
    sah: ["махтал", "maxtal"],
    tyv: ["четтирдим", "tɕetːirdim"],
    kjh: ["алғыс", "alɣɯs"],
    alt: ["быйан", "bɯjan"],
    cv: ["тав", "tav"],
    bxr: ["баярлаа", "bajarlaː"],
    mvf: ["bayarla-", "bajarla"],
    evn: ["пасиба", "pasiba"],
    eve: ["пасиба", "pasiba"],
    gld: ["банихан", "banihan"],
    ude: ["нюхча", "ɲuxt͡ʃa"],
    yrk: ["спасибо", "spasibo"],
    enf: ["spasibo", "spasibo"],
    nio: ["нюәдыра", "ɲuədɨra"],
    sel: ["пасьпе", "pasʲpe"],
    kca: ["пӑсиве", "pasive"],
    ckt: ["вэԓынкы", "weɫɯnkɯ"],
    kpy: ["ныӈэвыквын", "nɯŋewɯkwɯn"],
    itl: ["—", "—"],
    ykg: ["—", "—"],
    yux: ["пасьпе", "pasʲpe"],
    niv: ["туьмг", "tumɡ"],
    ket: ["асьх", "asʲx"],
    my: ["ကျေးဇူးတင်ပါတယ်", "tɕézú tìɴ bà dɛ̀"],
    km: ["អរគុណ", "ʔɔːkun"],
    lo: ["ຂອບໃຈ", "kʰɔːp˥ t͡ɕaj˩˧"],
    soa: ["ขอบใจ", "kʰɔːp˩˧ t͡ɕaj˩˧"],
    yo: ["ẹ ṣé", "ɛ ʃé"],
    zu: ["ngiyabonga", "ŋijaɓoŋɡa"],
    am: ["አመሰግናለሁ", "amɛsɛɡnalɛhu"],
    aiw: ["galatoma", "ɡalatoma"],
    sgw: ["ኣምስከነለንት", "amɨskɛnɛlɛnt"],
    mg: ["misaotra", "misautɾa"],
    ain: ["イヤイライケレ", "ijairaːikeɾe"],
    fi: ["kiitos", "kiːtos"],
    hu: ["köszönöm", "køsønøm"],
    ohu: ["kȍszȍnèm", "køsønɛm"],
    el: ["ευχαριστώ", "efxaɾisto"],
    nl: ["dank je", "dɑŋk jə"],
    pl: ["dziękuję", "d͡ʑɛŋˈkujɛ"],
    szl: ["dziynkuja", "ˈd͡ʑɨŋkuja"],
    uk: ["дякую", "dʲɑkuju"],
    sv: ["tack", "takː"],
    no: ["takk", "tɑkː"],
    da: ["tak", "tʰaɡ"],
    ro: ["mulțumesc", "mult͡sumesk"],
    ga: ["go raibh maith agat", "ɡɔ ɾɛv mah aɡət"],
    eu: ["eskerrik asko", "eskerik asko"],
    cy: ["diolch", "diːɔlx"],
    ka: ["მადლობა", "madloba"],
    lzz: ["ბერეკეთი", "berekʰetʰi"],
    sva: ["ხოჩამდ", "xotʃamd"],
    laz: ["ნოღამე", "noɣame"],
    hy: ["շնորհակալություն", "ʃnoɾhɑkɑlutʰjun"],
    hyw: ["շնորհակալութիւն", "ʃnoɾhɑɡɑluˈtʰjun"],
    nv: ["ahéheeʼ", "ɑhéːheːʔ"],
    koy: ["baasee'", "baːseːʔ"],
    haw: ["mahalo", "mahalo"],
    mi: ["ngā mihi", "ŋaː mihi"],
    qu: ["sulpayki", "sulpajki"],
    zh_db: ["谢谢", "ɕjɛ˥˩ɕjɛ"],
    zh_sc: ["谢谢", "ɕie˥˩ɕie"],
    cdo: ["谢谢", "sia˧˧sia"],
    bo: ["ཐུགས་རྗེ་ཆེ", "tʰuːt͡ɕi˥ t͡ɕʰe˥"],
    bft: ["བཀའ་དྲིན་ཆེ", "kadrintɕʰe"],
    lbj: ["ཐུགས་རྗེ་ཆེ", "tʰuktɕetɕe"],
    khg: ["ཐུགས་རྗེ་ཆེ", "tʰukdʑe tɕʰe"],
    cnd: ["namaste", "namaste"],
    ii: ["ꃰꊿ", "ka˧˧tɕʰɿ˧˧"],
    azo: ["katɕʰɿ", "katɕʰɿ˧˧"],
    hni: ["gaq sai", "ɡaq sai"],
    th_isan: ["ขอบใจ", "kʰɔːp˨˩t͡ɕaj˥"],
    th_n: ["ขอบคุณ", "kʰɔːp˨˩kʰun˥"],
    th_s: ["ขอบคุณ", "kʰɔːp˨˩kʰun˥"],
    za: ["dwgrengz mwngz", "tuk˧ɣeŋ˧˥mɯŋ˧˥"],
    hmn: ["ua tsaug", "uã˥tɕɑu˧"],
    jv: ["matur nuwun", "matur nuwun"],
    jvn: ["matur nuwun", "matur nuwun"],
    su: ["hatur nuhun", "hatur nuhun"],
    ceb: ["salamat", "salamat"],
    ilo: ["agyamanak", "aɡjamanak"],
    fj: ["vinaka", "vinaka"],
    rtm: ["fai'aksia", "faiʔaksia"],
    sm: ["faʻafetai", "faʔafetai"],
    to: ["mālō", "maːloː"],
    pau: ["sulang", "sulaŋ"],
    sd: ["مهرباني", "meːrbɑːniː"],
    pa: ["ਧੰਨਵਾਦ", "dənːʋɑːd"],
    pnb: ["شکریہ", "ʃʊkɾɪjɑː"],
    ne: ["धन्यवाद", "dʱənjəbaːd"],
    dty: ["धन्यवाद", "dʱənjəbaːd"],
    kfx: ["धन्यवाद", "dʱənjəʋaːd"],
    mr: ["धन्यवाद", "dʱənjəʋaːd"],
    lmn: ["धन्यवाद", "dʱənjaβaːd"],
    gu: ["આભાર", "aːbʱaːɾ"],
    si: ["ස්තූතියි", "stuːtɪjɪ"],
    dv: ["ޝުކުރިއްޔާ", "ʃukurijjaː"],
    te: ["ధన్యవాదాలు", "dʱənjəʋaːdaːlu"],
    kn: ["ಧನ್ಯವಾದ", "dʱənjəʋaːdə"],
    ml: ["നന്ദി", "nəndi"],
    tg: ["раҳмат", "rɒhmɒt"],
    ku: ["spas", "spɑːs"],
    ckb: ["سوپاس", "supɑːs"],
    sdh: ["سپاس", "spɑːs"],
    ps: ["مننه", "mənəna"],
    az: ["təşəkkür", "tæʃecːyɾ"],
    azb: ["ساغ اول", "saɣ ol"],
    gag: ["saa ol", "saː ol"],
    ug: ["رەھمەت", "ɾɛhmɛt"],
    kk: ["рахмет", "ɾɑxmet"],
    ky: ["рахмат", "ɾɑxmɑt"],
    uz: ["rahmat", "ɾɑxmɑt"],
    tk: ["sagboluň", "sɑɡboluŋ"],
    mn_cn: ["ᠪᠠᠶᠠᠷᠯᠠᠯ᠎ᠠ", "bɑjɑrlɑlɑ"],
    mnc: ["ᠪᠠᠨᡳᡥᠠ", "banixa"],
    sjo: ["ᠪᠠᠨᡳᡥᠠ", "banixa"],
    ar_eg: ["شكراً", "ʃokɾan"],
    ar_lev: ["شكراً", "ʃukɾan"],
    ar_gulf: ["مشكور", "maʃkuːɾ"],
    ar_iq: ["شكراً", "ʃukɾan"],
    ar_ma: ["شكراً", "ʃukɾan"],
    arq: ["صحة", "sˤəħħa"],
    mey: ["شكرا", "ʃukran"],
    ar_tn: ["عيّشك", "ʕajːʃək"],
    ar_sd: ["شكراً", "ʃukɾan"],
    ti: ["የቐንየለይ", "jɛqɛnjɛlɛj"],
    mt: ["grazzi", "ɡɾatt͡si"],
    ig: ["daalụ", "daːlʊ"],
    bom: ["gèyak", "ɡejak"],
    tiv: ["m sugh u", "m suɣ u"],
    efi: ["sọsọñọ", "sɔsɔɲɔ"],
    ekp: ["imela", "imela"],
    izi: ["ima ego", "ima eɡo"],
    ibb: ["sọsọñọ", "sɔsɔŋɔ"],
    urh: ["miguo", "miɡuo"],
    dge: ["nani", "nani"],
    ets: ["oyabuwere", "ojabuweɾe"],
    iso: ["migwo", "miɡwo"],
    ha: ["na gode", "na ɡode"],
    xed: ["ʔusi", "ʔusi"],
    ker: ["shùkūr", "ʃukuːɾ"],
    dbq: ["ndzaŋ", "ndzaŋ"],
    wo: ["jërëjëf", "dʒəɾədʒəf"],
    srr: ["jaaraama", "dʒaːɾaːma"],
    so: ["mahadsanid", "maħadsanid"],
    om: ["galatoomi", "ɡalatoːmi"],
    kxc: ["galta", "ɡalta"],
    drs: ["galaata", "ɡalaːta"],
    dsh: ["galche", "ɡaltʃe"],
    rw: ["murakoze", "muɾakoze"],
    rn: ["murakoze", "muɾakoze"],
    xh: ["enkosi", "ɛnkosi"],
    sn: ["maita", "maita"],
    mxc: ["mazviita", "mazviita"],
    ln: ["matɔ́ndɔ", "matɔndɔ"],
    ny: ["zikomo", "zikomo"],
    yao: ["nakwete", "nakwete"],
    en_aave: ["thanks", "θæŋks"],
    en_nz: ["cheers", "t͡ʃiəz"],
    en_au: ["thanks", "θæːŋks"],
    sco: ["thanks", "θaŋks"],
    af: ["dankie", "daŋki"],
    de_gsw: ["Merci", "mɛrsiː"],
    de_at: ["Danke", "daŋkə"],
    de_by: ["Dangschee", "dɑŋʃeː"],
    gsw: ["Merci", "mɛrsi"],
    swg: ["Danggschee", "daŋkʃeː"],
    bar: ["Vagelts Gott", "fɐɡɛlts ɡɔt"],
    vmf: ["Vergelt's Gott", "fɛɐɡɛlts ɡɔt"],
    wae: ["Vergelts Gott", "fɛrɡɛlts ɡɔt"],
    nds: ["Dankschöön", "daŋkʃøːn"],
    ksh: ["Dankeschön", "daŋkəʃøːn"],
    pdc: ["Denki", "dɛŋki"],
    pdt: ["Donk", "dɔŋk"],
    yi: ["אַ דאַנק", "a daŋk"],
    is: ["takk", "tʰahk"],
    gd: ["tapadh leat", "tʰapə lʲɛt"],
    br: ["trugarez", "tɾyɡaɾes"],
    nap: ["grazie", "ɡratsjə"],
    scn: ["grazii", "ɡrattsii"],
    vec: ["grassie", "ɡrasje"],
    co: ["grazie", "ɡratsje"],
    lij: ["graçie", "ɡrasje"],
    rgn: ["gras", "ˈɡɾas"],
    egl: ["gràzie", "ˈɡɾaːtsje"],
    frp: ["mèrci", "mɛrsi"],
    ca: ["gràcies", "ɡɾasiəs"],
    gl: ["grazas", "ɡɾaθas"],
    oc: ["mercés", "merses"],
    be: ["дзякуй", "dʲzʲakuj"],
    cs: ["děkuji", "ɟɛkuji"],
    sk: ["ďakujem", "ɟakujɛm"],
    sl: ["hvala", "xʋaːla"],
    sr: ["хвала", "xʋala"],
    bg: ["благодаря", "blaɡɔdarʲa"],
    lt: ["ačiū", "ɐtʃʲuː"],
    sgs: ["ačiū", "atʃuː"],
    lv: ["paldies", "paldiɛs"],
    prg: ["dīnkun", "diːnkun"],
    sq: ["faleminderit", "falɛmindɛɾit"],
    aae: ["faleminderit", "falɛmindɛɾit"],
    et: ["tänan", "tænɑn"],
    ht: ["mèsi", "mɛsi"],
    jam: ["tanks", "taŋks"],
    bah: ["tank ya", "tank jə"],
    bzj: ["tanks", "taŋks"],
    pap: ["danki", "daŋki"],
    kea: ["obrigadu", "obriɡadu"],
    rom: ["nais tuke", "najs tukɛ"],
    rmy: ["najis tuke", "najis tuke"],
    rmf: ["naais", "naːis"],
    pcm: ["tanx", "taŋks"],
    tpi: ["tenkyu", "tɛŋkju"],
    ho: ["tanikiu", "tanikiʊ"],
    kmh: ["ñib", "ɲib"],
    kmu: ["susu", "susu"],
    emi: ["poasi", "poasi"],
    hot: ["fau", "fau"],
    fai: ["ngam ngam", "ŋam ŋam"],
    nlc: ["amole", "amole"],
    bzh: ["vog ehog", "voɡ ehoɡ"],
    tcs: ["eso", "ɛso"],
    pis: ["tagio", "taɡio"],
    hwc: ["tanks", "tæŋks"],
    se: ["giitu", "kiːtu"],
    sma: ["gæjhtoe", "kæjhtoe"],
    smj: ["gijttuo", "kijhtuə"],
    smn: ["tiittu", "tiːtːu"],
    sms: ["späʹsseb", "spæsːeb"],
    sjd: ["пасьпе", "pasʲpe"],
    vro: ["aitäh", "ɑitæh"],
    gn: ["aguyje", "aɡuɨʒe"],
    yrl: ["katu", "katu"],
    chr: ["ᎢᎴᎯᏍᏗ", "ilehisdi"],
    cay: ["niáwę", "niawɛ̃"],
    onn: ["nya:wę'", "njaːwɛ̃ʔ"],
    tus: ["nyaʼwę:", "ɲaʔwɛ̃ː"],
    as: ["ধন্যবাদ", "dʱɔnjɔbad"],
    or: ["ଧନ୍ୟବାଦ", "dʱɔnjɔbaːdɔ"],
    bho: ["धन्यवाद", "dʱənjəʋaːd"],
    en_south: ["thanks", "θæːŋks"],
    en_app: ["thanks", "θæŋks"],
    en_in: ["thanks", "tæŋks"],
    en_ie: ["thanks", "taŋks"],
    en_sco: ["thanks", "θaŋks"],
    en_yk: ["ta", "tɑː"],
    en_ck: ["fanks", "fæŋks"],
    en_sg: ["thanks", "tɛŋks"],
    fy: ["tankewol", "tɑŋkəvɔl"],
    frr: ["toonk", "toːŋk"],
    li: ["merci", "mɛrsi"],
    nn: ["takk", "tɑkː"],
    fo: ["takk", "tʰahk"],
    fr_qc: ["merci", "mɛʁsɪ"],
    fr_af: ["merci", "mɛʁsi"],
    fr_be: ["merci", "mɛʁsi"],
    fr_ch: ["merci", "mɛʁsi"],
    es_co: ["gracias", "ɡɾasjas"],
    es_cl: ["gracias", "ɡɾasjah"],
    es_ar: ["gracias", "ɡɾasjas"],
    es_cu: ["gracias", "ɡɾasjah"],
    es_pe: ["gracias", "ɡɾasjas"],
    es_an: ["gracias", "ɡɾasjah"],
    lad: ["grasias", "ɡɾasjas"],
    rm: ["grazia", "ɡratsia"],
    sc: ["gràtzias", "ɡrattsjas"],
    iu: ["ᓇᑯᕐᒦᒃ", "nakuʁmiːk"],
    la: ["grātiās", "ɡraːtiaːs"],
    el_grc: ["εὐχαριστῶ", "eukʰaristɔ̂ː"],
    el_kath: ["εὐχαριστῶ", "efxariˈsto"],
    egy: ["𓂧𓅱𓂝𓎡", "duːʕak"],
    en_ang: ["þancas", "θɑnkɑs"],
    enm: ["gramercy", "ɡraːmɛrsiː"],
    en_em: ["gramercy", "ɡraˈmɛrsi"],
    ang: ["þancian", "θɑntsiɑn"],
    ofs: ["thank", "θank"],
    non: ["þǫkk", "θɔkː"],
    got: ["𐌸𐌰𐌲𐌺𐍃", "θɑŋks"],
    cu: ["благодарьствоую", "blɑɡodɑrʲstvuju"],
    pi: ["अनुमोदामि", "anumodaːmi"],
    pi_edu: ["anumodanā", "anumodanaː"],
    pmh: ["—", "—"],
    cop: ["ϣⲉⲡϩⲙⲟⲧ", "ʃephmot"],
    arc: ["ܬܘܕܝ", "tawdiː"],
    amw: ["ܬܘܕܝ", "tawdiː"],
    aii: ["ܒܣܝܡܐ", "basima"],
    tsm: ["ܬܘܕܝ", "tawdi"],
    sux: ["—", "—"],
    akk: ["𒁲𒌅", "taʃlimtu"],
    hit: ["—", "—"],
    nci: ["tlazōhcāmati", "tɬasoːʰkaːmati"],
    nhx: ["tlazohcamati", "tlasoʔkamati"],
    nch: ["tlazohcamati", "tlasoʔkamati"],
    nhw: ["tlazohcamati", "tlasoʔkamati"],
    nhe: ["tlazohcamati", "tlasoʔkamati"],
    hch: ["pa'iwakaitsie", "paʔiwakaitsje"],
    ngu: ["tlazohcamati", "tlasoʔkamati"],
    ppl: ["padiush", "padjuʃ"],
    crn: ["atsipiraá", "atsipiraː"],
    myn: ["nibʼoolal", "nibʼoːlal"],
    ine: ["—", "—"],
    zh_song: ["謝", "ɕjɛ˥˩"],
    zh_wenyan_edu: ["謝", "tsɛ˨"],
    zh_han: ["謝", "ziɛ"],
    zh_tang: ["謝", "ziɛH"],
    ja_edo: ["忝い", "katadʑikenai"],
    ja_kanbun: ["謝す", "ɕasu"],
    ja_heian: ["忝なし", "katadikenaɕi"],
    ja_chu: ["忝し", "katadʑikenaɕi"],
    pry: ["—", "—"],
    ko_mid: ["고맙ᄉᆞᆸ나이다", "komap.sʌp.na.i.ta"],
    oko: ["—", "—"],
    okg: ["—", "—"],
    ko_gor: ["—", "—"],
    ko_em: ["고맙소이다", "komap.so.i.da"],
    vi_han: ["謝", "ta˨˩˨"],
    vi_nom: ["感恩", "kaːm əːn"],
    eo: ["dankon", "dankon"],
    vo: ["danö", "danø"],
    ina: ["gratias", "ɡɾatjas"],
    ia: ["gratias", "ɡratias"],
    tok: ["pona", "pona"],
    tlh: ["qatlho'", "qʰɑt͡ɬʰoʔ"],
    jbo: ["ki'e", "kiʔe"],
    cjy: ["谢谢", "ɕie˨ɕie"],
    hsn: ["谢谢", "ɕie˩˧ɕie"],
    gan: ["谢谢", "ɕia˨˩ɕia"],
    mai: ["धन्यवाद", "dʱənjəbaːd"],
    anp: ["धइन्यवाद", "dʱainjəbaːd"],
    awa: ["धन्यवाद", "dʱənjəbaːd"],
    thr: ["धन्यवाद", "dʱənjəbaːd"],
    bra: ["धन्यवाद", "dʱənjəbaːd"],
    skr: ["شکریہ", "ʃukrijaː"],
    sat: ["ᱫᱷᱚᱱᱭᱚᱵᱟᱫ", "dʱonjobad"],
    kru: ["धोन्नोबाद", "dʱonːobaːd"],
    mad: ["tarèma kasè", "tarɛma kasɛ"],
    hil: ["salamat", "salamat"],
    cbk: ["gracias", "ˈɡɾasjas"],
    bal: ["مہربانی", "mehrabaːniː"],
    ak: ["medaase", "medaase"],
    ada: ["ojakuɛ", "odʒakwɛ"],
    gaa: ["oyiwala", "ojiwala"],
    nzi: ["medaase", "medaase"],
    mk: ["благодарам", "blaˈɡɔdaram"],
    lg: ["webale", "weːbale"],
    zne: ["oni-tambua", "oni-tambua"],
    myx: ["ole nise", "ole nise"],
    bxk: ["orio", "orio"],
    ki: ["nĩ wega", "ni weɡa"],
    mer: ["nĩ baba", "ni baba"],
    kam: ["nĩ vinya", "ni viɲa"],
    ebu: ["nĩ baba", "ni baba"],
    tn: ["ke a leboga", "ke a leboɣa"],
    st: ["kea leboha", "kea leboha"],
    ts: ["inkomu", "iŋkomu"],
    ve: ["ndo livhuwa", "ndo livʱuwa"],
    bem: ["natotela", "natotela"],
    kqn: ["nasakwilila", "nasakwilila"],
    lua: ["tuasakidila", "tuasakidila"],
    kg: ["matondo", "matondo"],
    lol: ["olɛli", "olɛli"],
    tll: ["toleko", "toleko"],
    ff: ["a jaaraama", "a dʒaːɾaːma"],
    bm: ["i ni ce", "i ni tʃe"],
    ddn: ["biguƞ", "biɡũ"],
    emk: ["i ni se", "i ni se"],
    kao: ["i ni baara", "i ni baːɾa"],
    snk: ["inkawu", "iŋkawu"],
    mwk: ["i ni baara", "i ni baːɾa"],
    mlq: ["i ni baara", "i ni baːɾa"],
    mev: ["nyɛŋ", "ɲɛŋ"],
    dnj: ["kpe", "kpe"],
    ses: ["barka", "barka"],
    khq: ["barka", "barka"],
    dje: ["fofo", "fofo"],
    kab: ["tanemmirt", "tænəmːiɾt"],
    yua: ["dios boʼotik", "dios boʔotik"],
    ncs: ["—", "—"],
    itz: ["dios b'otik", "dios botik"],
    usp: ["maltyox", "maltjoʃ"],
    tzo: ["kolaval", "kolaval"],
    tzh: ["wokol awal", "wokol awal"],
    mix: ["tachu'un", "tatʃuʔun"],
    zap: ["xtiozenu", "ʃtjozenu"],
    zts: ["xclen lo'", "ʃklen loʔ"],
    maz: ["ndios", "ndios"],
    xtm: ["tachu'un", "tatʃuʔun"],
    mxv: ["tatu'un", "tatuʔun"],
    toc: ["pa'xkatkatsiniyán", "paʔʃkatkatsinijan"],
    huv: ["mongoy", "moŋoj"],
    ay: ["yuspagara", "juspaɣaɾa"],
    jaq: ["yuspaa", "juspaː"],
    cni: ["naranki", "naɾaŋki"],
    ame: ["gracia", "ɡɾasia"],
    gym: ["kuin", "kuin"],
    sum: ["yaisi", "jaisi"],
    jiv: ["yuminsajme", "juminsadʒme"],
    agr: ["see", "sɛː"],
    acu: ["mai-tikut", "majtikut"],
    car: ["irombo", "iɾombo"],
    pbb: ["pay", "paj"],
    gum: ["payn", "pajn"],
    arn: ["chaltu", "tʃaltu"],
    cr: ["ᑭᓇᓈᐢᑯᒥᑎᐣ", "kinanaːskomitin"],
    chp: ["mahsi cho", "mahsi tʃo"],
    oj: ["miigwech", "miːɡʷetʃ"],
    atj: ["mikwetc", "mikwetʃ"],
    mic: ["wela'lin", "welaʔlin"],
    pqm: ["woliwon", "woliwon"],
    abe: ["wliwni", "wliwni"],
    umu: ["wanìshi", "waniʃi"],
    crk: ["ᐦᐊᐃᐧ", "haj-haj"],
    yur: ["wokhlew", "wokʰlew"],
    lkt: ["philámayaye", "pʰilámajaje"],
    kl: ["qujanaq", "qujanaq"],
    ce: ["баркалла", "baɾkalːa"],
    inh: ["баркал", "baɾkal"],
    av: ["баркала", "baɾkala"],
    lez: ["чухсагъул", "tʃuxsaʁul"],
    dar: ["баркалла", "baɾkalːa"],
    agx: ["баркалла", "baɾkalːa"],
    ddo: ["баркалла", "baɾkalːa"],
    lbe: ["барчаллагь", "baɾtʃalːaʁ"],
    tab: ["чухсагъул", "tʃuxsaʁul"],
    aqc: ["хӀама", "ħama"],
    udi: ["бахтӏам", "baχtʼam"],
    tkr: ["бахытыд", "baxətəd"],
    kum: ["савбол", "savbol"],
    nog: ["саьоьлин", "sɵlin"],
    ady: ["тхьауегъэпсэу", "tħawajaʁapsaw"],
    kbd: ["фӏыщӏэ", "fʼɪʃʼa"],
    ab: ["иҭабуп", "itʼabup"],
    abq: ["таабит", "taːbit"],
    uby: ["—", "—"],
    xmf: ["გიდიდი", "ɡididi"],
    os: ["бузныг", "buznəɡ"],
    ty: ["māuruuru", "maːuɾuʔuɾu"],
    niu: ["fakaaue", "fakaaue"],
    tvl: ["fakafetai", "fakafetai"],
    rap: ["maururu", "mauɾuɾu"],
    rar: ["meitaki", "meitaki"],
    mh: ["koṃṃool", "komˠːoːlˠ"],
    gil: ["ko rabwa", "ko ɾabʷa"],
    ch: ["si yu'os ma'åse'", "si juʔos maʔaːseʔ"],
    tet: ["obrigadu", "obɾiɡadu"],
    tdt: ["obrigadu", "obɾiɡadu"],
    aoz: ["neno biluk", "neno biluk"],
    bi: ["tankyu", "taŋkju"],
    pip: ["tankyu", "taŋkju"],
    pjt: ["palya", "palja"],
    wbp: ["ngantitu", "ŋantitu"],
    piu: ["palya", "palja"],
    aer: ["unte mwerre", "untɛ mʷɛɾɛ"],
    nha: ["marlu", "maɻlu"],
    olg: ["marlu", "maɻlu"],
    adt: ["mukunha", "mukuɲa"],
    nys: ["boordawan", "boːɻdawan"],
    xul: ["miyamala", "mijamala"],
    wbt: ["walytjarra", "waʎcaɻa"],
    mni: ["ꯊꯥꯒꯠꯆꯔꯤ", "tʰaːɡattʃaɾi"],
    bpy: ["ধইন্যবাদ", "dʱoinjobaːd"],
    new: ["सुभाय", "subʱaj"],
    lif: ["ᤐᤡᤍᤠᤱ", "pidaːŋ"],
    tdh: ["धन्यवाद", "dʱənjəbaːd"],
    brx: ["साबार", "sabaɾ"],
    adi: ["nasi", "nasi"],
    nag: ["dhonyobad", "dʱoɲobad"],
    nzm: ["kazi", "kazi"],
    nmf: ["ase", "ase"],
    lus: ["ka lawm e", "ka lawm e"],
    dz: ["བཀྲིན་ཆེ", "kadrintɕe"],
    xsr: ["ཐུགས་རྗེ་ཆེ", "tʰuktɕetɕʰe"],
    xkz: ["kadrinche", "kadrintɕe"],
    sik: ["ཐུགས་རྗེ་ཆེ", "tʰuktɕetɕe"],
    min: ["tarimo kasiah", "taɾimo kasiah"],
    nia: ["saohagölö", "saohaɡølø"],
    ban: ["matur suksma", "matuɾ suksma"],
    ace: ["trimong gaséh", "tɾimoŋ ɡasɛh"],
    gay: ["matur sangat", "matuɾ saŋat"],
    bug: ["kuru sumange", "kuɾu sumaŋe"],
    mdr: ["kuru' sumanga'", "kuɾuʔ sumaŋaʔ"],
    war: ["salamat", "salamat"],
    bik: ["dios mabalos", "dios mabalos"],
    bto: ["dyos mabalos", "djos mabalos"],
    tum: ["yewo", "jewo"],
    kde: ["nashukuru", "naʃukuɾu"],
    seh: ["ndatenda", "ndatenda"],
    ngl: ["ekoshelele", "ekoʃelele"],
    din: ["alanyiek", "alaɲiek"],
    nus: ["lɛrnyä", "lɛɾɲa"],
    anu: ["apwoyo", "apwojo"],
    luo: ["erokamano", "erokamano"],
    mas: ["ashe", "aʃe"],
    aue: ["ho‖é", "hoǁé"],
    bfa: ["mungari", "muŋɡari"],
    saq: ["ashe", "aʃe"],
    aa: ["qungúsa", "quŋɡusa"],
    shi: ["tanmmirt", "tanmːiɾt"],
    rif: ["tanmirt", "tanmiɾt"],
    shy: ["tanmirt", "tanmiɾt"],
    mwr: ["धन्यवाद", "dʱənjəbaːd"],
    bgc: ["धन्यवाद", "dʱənjəbaːd"],
    ks: ["شُکریہ", "ʃukrijaː"],
    kok: ["देव बरें करूं", "deʋ bəɾẽ kəɾũ"],
    mnp: ["多谢", "to˥˦sia˨˨"],
    nan_te: ["感谢", "kam˥˧sia˩˩"],
    yue_ts: ["多谢", "ɔ˨˨ɬɛ˧˨"],
    czh: ["谢谢", "ɕie˦˦ɕie"],
    cnp: ["多谢", "tɔ˦˦tsɛ˦˦"],
    zh_jh: ["谢谢", "ɕje˦˦ɕje"],
    zh_tj: ["谢谢", "ɕjɛ˥˩ɕjɛ"],
    zh_lz: ["谢谢", "ɕjɛ˨˦ɕjɛ"],
    dng: ["дуәще", "duəɕe"],
    hsb: ["dźakuju so", "ˈd͡ʑakuju sɔ"],
    csb: ["dzãki", "ˈd͡zɔ̃ki"],
    rue: ["дякую", "ˈdʲakuju"],
    fur: ["graziis", "ˈɡraːt͡sjis"],
    ast: ["gracies", "ˈɡɾaθjes"],
    ext: ["gracias", "ˈɣɾasjas"],
    fla: ["gracias", "ˈɣɾasjas"],
    an: ["gracias", "ˈɡɾaθjas"],
    rup: ["harauâ", "haˈrawɨ"],
    ruq: ["hăirau", "hɨiˈrau"],
    wa: ["mèrci", "mɛɾˈsi"],
    kpv: ["аттьӧ", "atʲtʲɵ"],
    koi: ["аттьӧ", "atʲtʲɵ"],
    udm: ["тау", "tau"],
    mhr: ["тау", "tau"],
    mrj: ["таусола", "tau sola"],
    myv: ["сюкпря", "sʲukprʲa"],
    mdf: ["сюкпря", "sʲukprʲa"],
    krl: ["passibo", "ˈpassibo"],
    olo: ["passibo", "ˈpassibo"],
    vep: ["spasib", "ˈspasib"],
    vot: ["passibo", "ˈpasːibo"],
    liv: ["tienū", "tiɛnuː"],
    mzn: ["مرسی", "mɛɾsi"],
    glk: ["مرسی", "mɛɾsi"],
    lrc: ["مرسی", "mɛɾsi"],
    crh: ["sağ ol", "saɣ ol"],
    tt: ["рәхмәт", "ræxmæt"],
    ba: ["рәхмәт", "ræxmæt"],
    krc: ["сау бол", "saw bol"],
    ksw: ["တၢ်ဘျုး", "ta bju"],
    pwo: ["တၢ်ဘျုး", "ta pju"],
    lhu: ["a-bo-shaˇ", "abôʃâʔ"],
    lis: ["ti-tu", "titu"],
    nxq: ["jjuq jjuq", "d͡ʑɯ˨˩d͡ʑɯ˨˩"],
    shn: ["ၶွပ်ႈၸႂ်", "kɔp tsai"],
    jia: ["χaːi", "χaːi"],
    kbp: ["agɔndɩ", "aɡɔndɩ"],
    ee: ["akpe", "akpe"],
    gej: ["akpe", "akpe"],
    aja: ["amɛ akpe", "amɛ akpe"],
    nyn: ["webare", "webare"],
    cgg: ["webare", "webare"],
    ttj: ["webale", "webale"],
    nyo: ["webale", "webale"],
    luy: ["orio", "orio"],
    ssw: ["ngiyabonga", "ŋijaɓoŋɡa"],
    nbl: ["ngiyathokoza", "ŋijatʰokoza"],
    nd: ["ngiyabonga", "ŋijaɓoŋɡa"],
    nso: ["ke a leboga", "kealeboɣa"],
    fan: ["akiba", "akiba"],
    naq: ["aios", "aios"],
    hts: ["ʼmbweko", "ʔmbweko"],
    nmn: ["—", "—"],
    kr: ["gushibe", "ɡuʃibe"],
    men: ["bisɛ", "bisɛ"],
    vai: ["ꖢꕜ", "sɛda"],
    tem: ["sɔŋ", "sɔŋ"],
    dyu: ["i ni ce", "i ni tʃe"],
    bbo: ["baraka", "baɾaka"],
    spp: ["fenge", "feŋɡe"],
    sus: ["inu wali", "inu wali"],
    syl: ["শুকরিয়া", "ʃukria"],
    rhg: ["shukoría", "ʃukria"],
    ctg: ["শুকরিয়া", "ʃukrija"],
    mag: ["धन्यवाद", "dʱənjəbaːd"],
    doi: ["धन्यवाद", "dʱənjəbaːd"],
    xkk: ["ɔrkun", "ʔɔrkun"],
    moh: ["niáwen", "niawen"],
    cho: ["yakoke", "jakoke"],
    mus: ["mvto", "mato"],
    esu: ["quyana", "qujana"],
    ipk: ["quyanaq", "qujanaq"],
    ess: ["игамсиқанаӄ", "iɡamsiqanaq"],
    ale: ["к̆аг̆аасак", "qaɣaːsak"],
    apw: ["ahéheʼe", "ʔaheːheʔe"],
    dak: ["pidámayaye", "pidámajaje"],
    chy: ["néá'eše", "néáʔeʃe"],
    arp: ["hohóu", "hohóu"],
    kio: ["gàu", "ɡàu"],
    lmo: ["gràzie", "ˈɡrasje"],
    pms: ["gràssie", "ˈɡrasːie"],
    eml: ["grazie", "ˈɡratsje"],
    mwl: ["oubrigado", "owβɾiˈɣadu"],
    pnt: ["ευχαριστώ", "efxariˈsto"],
    hno: ["شکریہ", "ʃukrija"],
    bhb: ["धन्यवाद", "dʱənjəbaːd"],
    cja: ["tarima kasih", "tarima kasiʔ"],
    hmo: ["tanikiu", "tanikiu"],
    meu: ["oi namo", "oi namo"],
    pon: ["kalahngan", "kalahŋan"],
    kos: ["kulo", "kulo"],
    myz: ["ࡈࡀࡁࡅࡕࡀ", "ʈabuta"],
    vmw: ["kosheni", "koʃeni"],
    dsb: ["źěkujom se", "ˈd͡ʑɛkujɔm sɛ"],
    gv: ["gura mie ayd", "ˈɡura miː eːd"],
    kw: ["meur ras", "mœːɾ ɾaːs"],
    zza: ["sıpas", "sɯpas"],
    brh: ["شکریہ", "ʃukɾijaː"],
    mrq: ["mauruuru", "mauɾuʔuɾu"],
    tiw: ["wuta-wani", "wutawani"],
    lbz: ["—", "—"],
    lbz_damin: ["—", "—"],
    nny: ["—", "—"],
    kky: ["—", "—"],
    guc: ["talé", "tale"],
    mch: ["enaña", "enaɲa"],
    wba: ["kase", "kase"],
    mzh: ["nehayij", "nehajix"],
    myp: ["kapiíhií", "kapiíhií"],
    tue: ["—", "—"],
    emp: ["bia bara", "bia baɾa"],
    kpe: ["balika", "balika"],
    bsq: ["mɔãĩ", "mɔãĩ"],
    loz: ["nitumezi", "nitumezi"],
    bbc: ["mauliate", "mauliate"],
    bts: ["diatebei", "diatebei"],
    akb: ["mauliate", "maulate"],
    bjn: ["tarima kasih", "tarima kasih"],
    abs: ["tarima kase", "tarima kase"],
    max: ["tarima kase", "tarima kase"],
    mui: ["terimo kasih", "terimo kasih"],
    sas: ["tampi asih", "tampi asih"],
    kha: ["khublei shibun", "kʰublei ʃibun"],
    mns: ["пасипа", "pasipa"],
    mrw: ["salamat", "salamat"],
    tsg: ["magsukul", "maɡsukul"],
    yap: ["kammagar", "kamːaɡar"],
    chk: ["kinisou", "kinisou"],
    gbm: ["धन्यवाद", "dʱənjəbaːd"],
    kfy: ["धन्यवाद", "dʱənjəbaːd"],
    xnr: ["धन्यवाद", "dʱənjəbaːd"],
    hr: ["hvala", "ˈxʋaːla"],
    bs: ["hvala", "ˈxvala"],
    iba: ["terima kasih", "terima kasih"],
    ljp: ["tarima kasih", "tarima kasih"],
    tzm: ["tanmmirt", "tanmːiɾt"],
    tmh: ["tanǝmmirt", "tanəmːirt"],
    ng: ["tangi", "taŋɡi"],
    kj: ["pandula", "pandula"],
    umb: ["twalipata", "twalipata"],
    kmb: ["kishukutu", "kiʃukutu"],
    lue: ["nasakwilila", "nasakwilila"],
    her: ["okuhepa", "okuhepa"],
    xal: ["ханҗанав", "xandʒanav"],
    sg: ["singila", "siŋɡila"],
    toi: ["twalumba", "twalumba"],
    peo: ["—", "—"],
    ave: ["—", "—"],
    xto: ["—", "—"],
    txb: ["—", "—"],
    phn: ["𐤁𐤓𐤊", "barak"],
    uga: ["𐎁𐎗𐎋", "baːriku"],
    xlu: ["—", "—"],
    pal: ["𐭮𐭯𐭠𐭮", "spaːs"],
    fa_clas: ["سپاس", "sipaːs"],
    syc: ["ܫܘܒܚܐ", "ʃubħaː"],
    fro: ["merci", "mɛrˈsi"],
    fr_class: ["grâces", "ɡraːs"],
    it_dan: ["mercede", "merˈtʃede"],
    goh: ["—", "—"],
    gez: ["ምስጋና", "məsgaːnaː"],
    gmy: ["—", "—"],
    xct_litpr: ["ཐུགས་རྗེ་ཆེ", "tʰukdʑe tɕʰe"],
    xct: ["ཐུགས་རྗེ་ཆེ", "tʰukdʒe tɕʰe"],
    xpu: ["𐤁𐤓𐤊", "barak"],
    xhu: ["𒀀𒅆", "aʃi"],
    elx: ["𒇷𒄩𒊑", "lihari"],
    xsa: ["𐩦𐩫𐩧", "ʃakar"],
    kaw: ["ꦤꦸꦮꦸꦤ꧀", "nuwun"],
    kho: ["𑀧𑁆𑀬𑀰𑁆𑀢", "pjaʃta"],
    de_lut: ["Danck", "daŋk"],
    gmh: ["—", "—"],
    es_sgl: ["gracias", "ˈɡɾat͡sjas"],
    osp: ["mercedes", "meɾˈʦeðes"],
    okz: ["អនុមោទនា", "ʔanumoːtəna"],
    osx: ["—", "—"],
    smg: ["nashukulu", "naʃukulu"],
    mos: ["barka", "barka"],
    maw: ["barika", "barika"],
    kln: ["kongoi", "koŋoi"],
    mfe: ["mersi", "meɾsi"],
    rcf: ["mersi", "mɛʁsi"],
    crs: ["mersi", "mɛʁsi"],
    gcf: ["mèsi", "mɛsi"],
    mnk: ["abaraka", "abaraka"],
    bqi: ["ممنون", "mamnun"],
    unr: ["dhonyobad", "dʱoɲobad"],
    hoc: ["dhanybad", "dʱanjbad"],
    enq: ["yaku", "jaku"],
    xpr: ["spās", "spaːs"],
    xqa: ["tabug", "tabuɡ"],
    sga: ["atloirgaim", "atloiɾɡim"],
    bsk: ["shukria", "ʃukrija"],
    yag: ["рахмат", "rahmat"],
    srn: ["grantangi", "ɡrantaŋi"],
    djk: ["gaantangi", "ɡaːntaŋi"],
    srm: ["waáwa", "waːwa"],
    kwk: ["gilakas'la", "ɡilakasla"],
    blc: ["—", "—"],
    sad: ["musʼokoyo", "muʃokojo"],
    pcc: ["gangzhainh", "ɡaŋ˩˩haiŋ˧˩"],
    iuu: ["laengz", "laŋ˨˧"],
    hui: ["wei", "wei"],
    tkl: ["fakafetai", "fakafetai"],
    squ: ["huy chexw a", "huj tʃexʷ a"],
    mga: ["atloirgaim", "atloiɾɡim"],
    hbo: ["תודה", "toːðaː"],
    he_mis: ["תודה", "todɑ"],
    hy_grab: ["շնորհակալութիւն", "ʃnoɾhɑkɑlutʰiwn"],
    mpt: ["hok", "hok"],
    ygr: ["tega", "teɡa"],
    roo: ["—", "—"],
    quz: ["añay", "aɲaj"],
    quy: ["agradecekuyki", "aɡradesekujki"],
    shp: ["gracias", "ɡrasjas"],
    cab: ["seremein", "seremein"],
    crx: ["snachailya", "snatʃailja"],
    tsi: ["t'oyaxsut nüsm", "tʼojaχsut nyzm"],
    thp: ["kukstéyp", "kuksteːjp"],
    wbl: ["ишкур", "iʃkur"],
    psi: ["شکریه", "ʃukrija"],
    bgq: ["धन्यवाद", "dʱanjabaːd"],
    laj: ["apwoyo", "apwojo"],
    ach: ["apwoyo", "apʷojo"],
    rki: ["ကျေးဇူးတင်ပါတယ်", "tɕézú tìɴ pà dɛ̀"],
    cnh: ["ka lawm", "ka lawm"],
    kxm: ["អរគុណ", "ʔɔːkun"],
    xng: ["ᠪᠠᠶᠠᠷᠯᠠᠪᠠ", "bajarlaba"],
    ja_kg: ["ありがとさげもす", "aɾiɡatosaɡemosɯ"],
    ja_sd: ["どうもね", "doːmone"],
    ko_hg: ["고마와", "komawa"],
    ko_jl: ["고맙당께", "komap̚t͈aŋkːe"],
    nan_pn: ["多謝", "to˥˥sia˩˩"],
    mra: ["knɔŋ", "knoŋ"],
    wuu_nb: ["谢谢", "ɕia˨˧ɕia"],
    yue_gz: ["多谢", "tɔ˥˥tsɛ˨˨"],
    khb: ["ᦀᦸᧃᦷᦓᧁ", "ʔɔn nau"],
    blt: ["ꪒꪲ ꪎꪶꪙ", "dʒɔp tʃai"],
    pam: ["dakal a salamat", "dakal a saˈlamat"],
    pag: ["salamat", "saˈlamat"],
    mdh: ["sukran", "ˈsukɾan"],
    gor: ["terima kasih", "teɾima ˈkasih"],
    mak: ["tarima kasi", "taɾima ˈkasi"],
    fon: ["àwǎnú", "àwǎnú"],
    kri: ["tɛnki", "ˈtɛŋki"],
    dag: ["mpaɣya", "mpaɣja"],
    xog: ["weebale", "weːbale"],
    teo: ["eyalama", "ejalama"],
    dyo: ["abara'k", "abaɾaʔk"],
    bci: ["moh", "mo"],
    tcy: ["ಸೊಲ್ಮೆಲು", "solmelu"],
    haz: ["تشکر", "taʃakkur"],
    tly: ["minnətdar", "minnətdaɾ"],
    kaa: ["rahmet", "ɾaχmet"],
    bej: ["baraʼoo", "baɾaʕoː"],
    tig: ["የቀንየለይ", "jəqanjəlej"],
    byn: ["ቀንየለይ", "qənjələj"],
    ssy: ["galatto", "ɡalatto"],
    ewo: ["akiba", "akiba"],
    bum: ["akiba", "akiba"],
    agq: ["ŋyaa'", "ŋjaːʔ"],
    mgo: ["nfɔn", "nfɔn"],
    dur: ["vɛɛɛ", "vɛːɛ"],
    ndc: ["ndatenda", "ndatenda"],
    ote: ["jamädi", "hamãdi"],
    otq: ["jamädi", "hamãdi"],
    tar: ["matéterabá", "mateteɾaba"],
    orv: ["—", "—"],
    xsc: ["—", "—"],
    sukh: ["—", "—"],
    xmr: ["—", "—"],
    onw: ["ⲡⲓⲥⲧⲁ", "pista"],
    cqu: ["añay", "aɲaj"],
    omc: ["—", "—"],
    chb: ["chibchachoa", "tʃibtʃatʃoa"],
    oma: ["—", "—"],
    osu: ["nuhun", "nuhun"],
    otl: ["ᜐᜎᜋᜆ᜔", "salamat"],
    zkt: ["—", "—"],
    juc: ["—", "—"],
    omx: ["—", "—"],
    pyx: ["—", "—"],
    obr: ["—", "—"],
    occ: ["—", "—"],
    och: ["謝", "*s.ɢAk-s"],
    ojp: ["—", "—"],
    pjk: ["—", "—"],
    vsa: ["—", "—"],
    txg: ["—", "—"],
    sog: ["—", "—"],
    otk: ["—", "—"],
    ami: ["aray", "arai"],
    pwn: ["masalu", "masalu"],
    tay: ["mhuway", "mhuwaj"],
    bnn: ["uninang", "uninaŋ"],
    trv: ["mhuway", "mhuwaj"],
    tsu: ["aveoveoyu", "aveoveoju"],
    tao: ["ayoy", "ajoi"],
    pyu: ["kasapakan", "kasapakan"],
    szy: ["lalumahan", "lalumahan"],
    ssf: ["mihu", "mihu"],
    hak_tw: ["承蒙你", "sin˩˩ muŋ˩˩ ŋi˩˩"],
    wuu_sz: ["谢谢", "ʑia˨˧˩ʑia"],
    wuu_wz: ["谢谢", "zia˨˩˧zia"],
    nan_qz: ["多謝", "to˨˨siaʔ˦˩"],
    nan_hai: ["多谢", "to˨˩jia˨˨"],
    zh_wh: ["谢谢", "ɕiɛ˥˧ɕiɛ"],
    zh_zz: ["谢谢", "ɕiɛ˨˩ɕiɛ"],
    hak_hl: ["承蒙你", "ʃin˨˦muŋ˨˦ŋi˨˦"],
    cpx: ["多谢", "to˧˧ɬia˥˧"],
    mfa: ["terimo kasih", "tərimo kaseh"],
    mtq: ["cám ơn", "kaːm ɤn"],
    tyz: ["cảm ơn", "kaːm˨˩˧ɤn˧˧"],
    kjp: ["တၢ်ဘျုး", "ta˧blu˧"],
    kac: ["chyeju kaba", "tʃedʒu˧kaba˧"],
    wbm: ["ban prix", "ban priʔ"],
    pll: ["kun cɔm", "kun tʃɔm"],
    ahk: ["gv ya", "ɡɯ˧ja˧"],
    dtp: ["pounsikou", "pounsikou"],
    hne: ["धन्यवाद", "dʱənjəwaːd"],
    mnw: ["တၚ်ဂုဏ်", "təŋ ɡɔn"],
    bru: ["kuhng", "kuhŋ"],
    bdq: ["kơbi", "kəbi"],
    lwl: ["kop khun", "kop kʰun"],
    grt: ["mittela", "mitːela"],
    nut: ["ơn rể", "ɤn˧˧zɛ˨˩˧"],
    quc: ["maltyox", "maltjoʃ"],
    cak: ["matyox", "matjoʃ"],
    kek: ["bantyox", "bantjoʃ"],
    poh: ["tioxlaab", "tjoʃlaːb"],
    kjb: ["yuhwal", "juhwal"],
    ctu: ["wokox", "wokoʃ"],
    toj: ["yuj", "juh"],
    bzd: ["wëʼs", "wəʔs"],
    cuk: ["nuedi malo", "nweðiː malo"],
    chf: ["dios bo'tik", "dios boʔtik"],
    agu: ["tixwajʼ", "tiʃwahʼ"],
    ixl: ["tantixh", "tantiʃ"],
    mam: ["chjonte", "tʃhonte"],
    mvc: ["chjonte", "tʃhonte"],
    wal: ["galatay", "ɡalataj"],
    sid: ["gali'ne", "ɡaliʔne"],
    tji: ["angzai", "aŋ˧˥t͡sai˥"],
    nij: ["sahindai", "sahindai"],
    sda: ["kurre sumanga'", "kurːe sumaŋaʔ"],
    lld: ["dilan", "diˈlaŋ"],
    stq: ["Bedoankje", "bəˈdɔːŋkjə"],
    wym: ["dynk śejn", "dɪnk ʃejn"],
    yuc: ["—", "—"],
    kgg: ["—", "—"],
    ota: ["تشكر ادرم", "teʃekˈkyɾ edeˈɾim"],
    cmg: ["ᠪᠠᠶᠠᠷᠯᠠᠯᠠ", "bajarlala"],
    ett: ["—", "—"],
    cms: ["—", "—"],
    xht: ["—", "—"],
    txr: ["—", "—"],
  },
};
